export const names = [
    "Brand Kit by Premast",
    "Namify",
    "Boring Avatars",
    "Be.Live",
    "Premast",
    "Good Landing Page",
    "LinkMngr",
    "Evolve",
    "Ctiny",
    "chaosMachine",
    "BrandBird",
    "How to NFT",
    "Sites",
    "Headers.me",
    "CopyAim",
    "Business Name Generator by Looka",
    "PFPMaker",
    "Alter",
    "Swag Fair",
    "BizCard",
    "Video Donut",
    "Eureka Surveys",
    "Core Studio° by Corebook.io",
    "Mentioned",
    "Pitch Deck Template for 2021",
    "Namejax",
    "Startup Stash",
    "Vidiwise",
    "Domain Point",
    "QR Menu Creator",
    "Bybrand - Create from scratch",
    "Booklets.io",
    "1Brand",
    "Figma Pitch Deck Template",
    "NameSnack",
    "Pizzly",
    "PodBooker",
    "First Search",
    "One Word Domains",
    "SaaS Pages",
    "Mailbum",
    "Carrd",
    "DrawKit",
    "LT Fan Platform",
    "Fiverr Logo Maker",
    "Brandmo",
    "One Profile",
    "Niice 3.0",
    "Startup Launch List",
    "Artboard Studio",
    "Screen Recorder - Snipclip",
    "Roadmap v.1.0",
    "Javelin by Lean Startup Machine",
    "Google Workspace",
    "Mobilo Wood",
    "Popl",
    "Zest",
    "Wavium 2.0",
    "Visably",
    "Landing Pages in MailChimp",
    "linkish",
    "Atomize React",
    "Artboard Studio 2.0",
    "Websites by MailerLite",
    "Huddle",
    "Brandful",
    "Make My Persona",
    "Premast Plus",
    "Logo Design for Indie Makers",
    "Namelix",
    "Looka (formerly Logojoy)",
    "WEBM To MP4",
    "Vectornator Pro For Mac",
    "Evolt Design Suite",
    "Welder",
    "Christmas Design Kit",
    "Freebie.Supply",
    "SaaS Startup Guide by Hotjar 🔥",
    "Urlefy",
    "Pexels Videos 3.0",
    "Unsplash for iOS",
    "Emblem",
    "Zoom Background Generator",
    "Mupixa 2.0",
    "UI Jar",
    "Resoundly",
    "Knowable Memberships",
    "Holographic Stickers by Sticker Mule",
    "Brandfetch",
    "DeckRobot for PowerPoint",
    "Plectica",
    "Fastory",
    "Dofo.com",
    "Duotone",
    "StartupResources.io",
    "Indians Who Code",
    "Just Launched",
    "Instagram Stories Widget - by Fastory",
    "RelayThat",
    "Sponstayneous",
    "Figma Color Search",
    "Influencer Sphere",
    "Brandy",
    "Speaker Directory by HeySummit",
    "AnyForm",
    "HiHello Backgrounds for Zoom",
    "SlidesPPT",
    "A brand new Dribbble",
    "HEROES JOBS",
    "Frontify",
    "VirtualOffice for Zoom",
    "BrandMentions 2.0",
    "Nexus",
    "The Coding Career Handbook",
    "APEX Scoring System",
    "Brandmark V2",
    "OpenStanding",
    "Guide to Video Marketing by Wistia",
    "LetsConnect",
    "Mobilo Metal Card",
    "Liinks",
    "illustrio",
    "Thea",
    "Kilo SSL",
    "Unique",
    "Cardanti Smart Business Card",
    "Slidebean 3.0",
    "ReleaseNotes",
    "Mailjoy",
    "Volv",
    "Patomic",
    "Playground",
    "Acrylic Charms by Sticker Mule",
    "Trend Watchers",
    "Awario",
    "Corebook.io",
    "Daily Say",
    "Automagical",
    "Pigment",
    "Namefruits",
    "Supercreative Profiles",
    "Namecheap Business Card Maker",
    "Try Cereals",
    "Uibot",
    "Animated Logos by Placeit",
    "Font Generator",
    "ZeBrand",
    "Logo Dust",
    "Font Fit",
    "GoodBrief",
    "Google Doc Publisher",
    "BuildBubbles",
    "DeepNamer",
    "How to Brand You",
    "Jona",
    "LinkedIn Review 2.0",
    "DrawAttention",
    "Gildform",
    "logos.porn",
    "illustrio 2.0",
    "Logo Foundry",
    "Dot Grid Notebook Black Edition",
    "Somebody.io",
    "Brand Building Guides & Tools",
    "Shopify Hatchful",
    "Battle of the Brands",
    "Pilcro",
    "😁.to",
    "Mural",
    "Teespring Direct",
    "Typography Resources",
    "Chatterbot",
    "StoriesAds.com",
    "Roameo",
    "The Brand Grader",
    "Stickerlight",
    "Coment",
    "Global Pass (by Coworker.com)",
    "NameBounce",
    "12 Ways To Stay Ahead Of The Competition",
    "BuildBubbles",
    "customDomainer",
    "Flick",
    "Startup Logo Archive",
    "Readory",
    "Notifier for Reddit",
    "Templates by 24Slides",
    "Brandmark",
    "Open Strategy",
    "Welcome",
    "Megabiz",
    "CREATE 5.0",
    "Dripkit Coffee 2.0",
    "HavePride.in",
    "Makr",
    "Packs by StartupThreads",
    "Sticker Mule Transfer Stickers",
    "Mobiz",
    "Unixstickers by Sticker Mule",
    "MOO Business Cards+",
    "NameRobot Toolbox",
    "Custom Illustrations by Design Pickle",
    "HeySpace",
    "Stop Wasting Time",
    "SVG Porn",
    "Brand.ai",
    "Naminum",
    "Standing Start Co.",
    "Seedproof",
    "Rona Games",
    "Cardify Essential",
    "Gloatt",
    "namewhale",
    "Enchᵅ",
    "Oqtor",
    "Clear labels by Sticker Mule",
    "AppLandr 2.0",
    "Onym",
    "Snorkel for Substack",
    "Intro",
    "Hatchful by Shopify",
    "Brandwagon by Wistia",
    "Logaster Company Name Generator",
    "Scout",
    "Visage 4.0",
    "The New Consumer",
    "PageRocket",
    "Straple",
    "Alitu",
    "Podsites",
    "Beamer",
    "Alertcamp",
    "Podcasts Makers",
    "OneLiners.co",
    "ScreenTray",
    "Ramp T-shirts",
    "TrelloMask",
    "Streamlabs Creator Sites",
    "Brand24 Mobile App 2.0",
    "Logomaster.ai",
    "Syften",
    "Holo",
    "Mixer",
    "Lumi",
    "We Are The Luminous",
    "Affinicasts",
    "Linkie",
    "HolaBrief Beta",
    "NameChk",
    "Pakible",
    "api.video",
    "Content Showcase",
    "Prostgles",
    "Toolbird",
    "Arka",
    "The Stacks",
    "LAMA",
    "Name2Inbox",
    "Ask Billie",
    "Venture360's Startup Fundraising Tool",
    "Picnic",
    "Startup Validator",
    "Logo Pizza",
    "Perksy",
    "Dogs'n'Sox",
    "Slash Packaging",
    "StartupDrugz",
    "PackMojo",
    "Create Brief",
    "Mule Sauce by Sticker Mule",
    "Priime",
    "Growth Hack Your Startup From 0 to 10k Users In A Month",
    "Wibber",
    "Draftss 2.0",
    "Lapparatus",
    "Chhota",
    "GIPHY Sticker Embed",
    "Scooped",
    "WiseIntro",
    "Rebout.me",
    "Envato Logo Kit",
    "Plugg",
    "GET ATTENTION",
    "Pixelixe",
    "Zoom Background Builder",
    "Brandie",
    "Die Cut Templates",
    "CentralBoard",
    "MojiLang",
    "Cardify",
    "Blipbrands",
    "Advencher Supply Co.",
    "Videobolt 3.0",
    "Custom Magnets by Sticker Mule",
    "Leon & George",
    "Skills",
    "FindTheCompany",
    "Beer Prints",
    "Yala",
    "Tailor Brands",
    "Design Rails",
    "Mural Collections",
    "Super Team Deluxe",
    "Collabor8",
    "JustSketchMe",
    "Ex-Out Creativity Handbook",
    "Adjustments",
    "DefeatBOCO - Research World",
    "Funder",
    "Possessions.",
    "StartupThreads Shopify App",
    "Georgette Packaging",
    "Domain Inferno",
    "AIFE.AI",
    "xroom.app",
    "Custom by Sock Club",
    "LonelyPage",
    "-",
    "Reward Attention",
    "Design for Business",
    "Brandpad",
    "Linkcard",
    "Reviewerly",
    "The Name App",
    "Herb & Olive",
    "Videobolt 2.0",
    "Tenta Browser 2.0",
    "Obsidian Premium Tees",
    "UpLevo",
    "Logophile",
    "Mention ✪ Insights Center",
    "Personal Print",
    "Un'kuppd Portable Pourover Coffee",
    "Draftss",
    "Gatekeepr",
    "AmpAve",
    "Mailjoy Letters",
    "terrible colors",
    "This is Broken",
    "Pupprrr",
    "News apps by PressPad",
    "Slidesome",
    "Gradient Joy",
    "Joy Milk Tea",
    "Flat Icon Generator 2.0",
    "HostEvent",
    "TAG : Next-Gen Social Network",
    "LivMo",
    "Wordoid",
    "Local mail by Mailjoy",
    "Waka Coffee",
    "Foo Fighters Sky",
    "Naming Matters",
    "bulk-mail CLI",
    "Knowee",
    "favico.js",
    "DrawAttention: The Blackboard",
    "Klasmic",
    "Houndr",
    "Galaxia",
    "Placeit Print",
    "Logo Design",
    "DataSkimmer",
    "Brand Trust Platform by Conversio",
    "Hipster Business Name",
    "Watermarker Pro",
    "Hook",
    "Safari Beauty Toolbar",
    "elStartup",
    "Tylio",
    "Moodie: Change your Mood",
    "Slogan Generator",
    "LogoHold",
    "raw.",
    "Deconditioning Stickers",
    "Posyt",
    "Zap",
    "Conceptboard",
    "Bittenfruit",
    "Swipe Designs",
    "43 Layers",
    "Instant Domain Search",
    "Tinder for Tinders",
    "Sesame Corporate Gifts",
    "Packamatic",
    "Greetabl for Business",
    "Hipster Logo Generator",
    "Visura.co",
    "Far Fetched Creations",
    "Made for Motion: Backpack & Packing Kit",
    "Go Jauntly",
    "Vyrill",
    "Web Push Notifications",
    "Lnky",
    "OnBrand Grader",
    "Hashletes",
    "Brandy",
    "MOO Letter Press Cards",
    "litty",
    "Vyrill VIP",
    "Base Deploy",
    "Underdog.io Workplaces",
    "Floom",
    "EmojiCatch",
    "ScrapeLogo",
    "Guide to Community Building",
    "Digital Profile",
    "Lanyard Market",
    "Harmany",
    "Squarespace Logo",
    "Meed Influencers",
    "Touristerguide Wand",
    "SoProSearch",
    "Sinup",
    "Captain Share",
    "LogoGraders",
    "Foliodot",
    "Quiddity",
    "Vrumble 2.0",
    "Slogan",
    "Zoklean",
    "Reddit Comment Embeds",
    "Openned By Erin",
    "Ace Tutor",
    "Emoji Rags",
    "Alerts by MarketSpace",
    "Like & Subscribe",
    "Pickit",
    "Ebroji",
    "BrandBucket",
    "Missions Dashboard from EyeEm",
    "Vidooya",
    "Lean Branding",
    "Name Geniuses",
    "Ruutly",
    "Instagram Marketing for Beginners",
    "Aim.io",
    "OneHoodie",
    "Fifty Square Feet Productions",
    "ThugStart",
    "InstantDJ",
    "Brand Identity Breakthrough",
    "Emotional Branding",
    "Chevrolet Co-Driver",
    "TIC - From Bonobos to the Warby Parker of Furniture",
    "Brand Ballers - Maintain a fresh website so your visitors have a good experience",
    "Breaking Down Your Business: School's Out!",
    "SMB Trust Rating",
    "What Makes A Great Brand & How To Cut Through All The Noise",
    "BRAND24",
    "Social Media",
    "Learn Educate Discover: Uttam Mukherjee, Brand Manager @P&G",
    "Ambition Today #14: Adam Besvinick Teaches How To Break Into Startups & Venture Capital",
    "Ambition Today - 15: How Patrick McGinnis",
    "Breaking Down Your Business Ep #190 - Kelly Jurecko",
    "Breaking Down Your Business Ep #172",
    "The Twenty Minute VC: Branko Cerny @ Immediately",
    "Digital Good Times - Ep 65 - Kerry Klassic of Intecoo - The Era of Brands & Influencer Marketing",
    "Seedcamp Podcast: Marketing Guru, Katy Turner",
    "FOMOFanz 006: How I Define Success in a Digital World",
    "Breaking Down Your Business Ep #189",
    "Breaking Down Your Business Ep #176",
    "Breaking Down Your Business Ep #177",
    "Create If Writing: How to Work with Brands and Tell Your Story in Sponsored Content",
    "Breaking Down Your Business - Driving Yourself Crazy?",
    "Hack To Start #124: Hailley Griffis, Communications Specialist, Buffer",
    "BrandBallers - #40 - Mike's first draft of a video script",
    "Learn Educate Discover: How To Build Your Brand Using Quora, Zach Pinnell, Founder @BlogToJob.com",
    "Breaking Down Your Business Ep #175",
    "Breaking Down Your Business - Ryan Dohrn",
    "Brand Boost Podcast - 162: Platforms that Drive Consumer Decisions",
    "Brand Ballers - Marketing: Who to target and how that affects website design",
    "The Notion Capital - 09: David Shearer, VP Marketing at Elevaate",
    "Be The Brand",
    "RGB – #20: RGBA Series 2",
    "Brand Ballers - Finding A Blog Process That Speeds Up Workflow",
    "Shopify Masters - How a PC Gamer Built a 7-Figure Business That Practically Runs Itself",
    "Hello Tech Pros: Lean Startup Process and Talent4Startups.org",
    "Boss Girl Creative: Defining Your Niche - Why You Should and/or Shouldn't",
    "Breaking Down Your Business - Ep #173",
    "Breaking Down Your Business - Ep #167",
    "Brand Ballers: What is a website and how it affects your brand",
    "BrandBallers Podcast #34 - Recap of our website series",
    "Breaking Down Your Business - Working OUT (Of The Office)",
    "BrandBallers Podcast - Episode 38",
    "Creative Pep Talk - Don't Chase The Glory",
    "Creative South Podcast - Bonus Episode - Hebah",
    "Breaking Down Your Business Ep #168",
    "Breaking Down Your Business - Lookin' Good",
    "Creative South Podcast - Episode 10 - Eric Friedensohn",
    "BrandBallers - How User Experience Affects Branding And What People Think About You",
    "Breaking Down Your Business Podcast Ep #170",
    "Brand Ballers: Setting Up Your Website Like A Restaurant",
    "TGIM - How SoulCycle’s Founders Built a Nationwide Movement Around Their Brand",
    "Breaking Down Your Business - Get In The Zone",
    "Breaking Down Your Business - It's Opposite Day! (No it's not)",
    "BrandBallers Podcast - #36",
    "Breaking Down Your Business Ep #171: Andrew Schulman",
    "BizDevShots Podcast - Turn the Ship Around – Go From a Leaky Deathtrap to a Luxury Yacht",
    "BrandBallers Podcast - BB#39",
    "BrandBallers #37 - How to structure videos",
    "Process - Episode 1 - Divvy Bike Share Chicago",
    "Breaking Down Your Business - Talk To Me",
    "Breaking Down Your Business - Group Hug",
    "BrandBallers Podcast - 24: Content Form",
    "Breaking Down Your Business - Get Out The Door (More)",
    "Breaking Down Your Business Podcast - Ep 166",
    "Dreamit Podcast - Startup Brand Building with Robin Albin & Brielle Pettinelli",
    "Objection Co"
]

export const taglines = [
    "Manage, share and create branded content in PowerPoint",
    "Meaningful brand names, free logo, social & domain check",
    "JavaScript library to generate SVG avatars based on text",
    "Live streaming app to make the whole world your studio",
    "Create presentations like never before",
    "Curation of 300+ best landing pages for design inspiration",
    "A complete link management and tracking solution",
    "Connect your card and earn up to 15% automatic cash back",
    "Short link, More control",
    "One-click unique graphics generator",
    "Brand your Twitter content uniquely",
    "Free resource for providing creators access to NFT",
    "No-code website building platform",
    "Create social cover images that get you followers",
    "AI copywriting & brainstorming for instant marketing copy",
    "Generate names, check availability, and see logo ideas",
    "Create an awesome profile pic from any photo",
    "Business name marketplace",
    "Sustainable swag made by small businesses",
    "Design smart & affordable paperless business cards",
    "Nail the welcome to your site with a stories-style video!",
    "Survey over 1 million people within minutes",
    "Online brand guidelines prototyping platform",
    "Get an email when your website is posted online.",
    "100+ investor approved slides for your pitch deck",
    "Curated brand marketplace for your next product",
    "A curated directory of 400 resources & tools for startups",
    "1-click video calls based on your visitor's journey, free",
    "Never pay for a premium domain again.",
    "Make a QR Code Menu for FREE",
    "Create an HTML email signature from scratch",
    "Bite sized learning for creatives",
    "Custom brand guidelines in moments",
    "The easiest way to build a compelling pitch deck in Figma",
    "Free business name generator",
    "Building API integrations has never been easier",
    "The easiest way to get booked on podcasts",
    "The world's best startup advice, curated and searchable.",
    "Database of 700K+ available and brandable one-word domains",
    "900+ Screenshots of the best SaaS landing pages",
    "Email signatures without the fuss",
    "Simple, responsive, one-page sites for pretty much anything.",
    "MIT licensed SVG illustrations, in 2 styles",
    "Blockchain fan engagement software for sports brands",
    "The first logo maker that is powered by actual designers",
    "Find the perfect brand name for any project",
    "Discontinued",
    "Netflix for your brand assets",
    "A​rticles you need to read before launching a startup.",
    "Online graphic design app mainly focused on product mockups.",
    "A minimal, ad-free screen recorder in your browser",
    "Radically transparent project & team management app.",
    "All-in-one platform for building products people want",
    "Gmail, Calendar, Drive, Docs, Sheets, Slides, Meet",
    "Smart business card made of wood",
    "Share your digital business card with a tap",
    "Collect feedback recordings from your users",
    "Your always up-to-date personal page",
    "Measure and improve your brand visibility in search.",
    "Easy to build, custom landing pages for free",
    "Turn boring bookmarks into embedded audio & video cards",
    "An open source design system for ReactJS",
    "Design, collaborate and present all in the browser",
    "Create a website in 1 day! Free no-code, drag & drop builder",
    "Get a pop-up team of expert designers and builders.",
    "Ready-made brands, crowd-sourced for your next startup",
    "A free buyer persona generator",
    "Access tons of design elements inside your PowerPoint",
    "A guide to create a great logo in 30 minutes or less 👩🏻‍🎨",
    "AI business name generator",
    "AI-powered logo maker",
    "Convert .webm files to .mp4 files without uploading them",
    "Vector graphic design software for macOS Catalina",
    "The design thinking suite to create great user experiences",
    "Record HQ content (podcast, etc..) for your startup remotely",
    "176 Figma Design Templates for startups",
    "Awesome free things for entrepreneurs & startups",
    "You have an MVP. Now what?",
    "URL shortener to monitor your business",
    "Free videos for everyone.",
    "High-res photos you can use freely for anything on iOS.",
    "Build your own beautiful brand",
    "Get a professional branded Zoom background in two clicks",
    "Remote usability testing, eye tracking, heatmaps, replays",
    "Hand-picked design inspiration for your real life projects",
    "Start a podcast without recording a thing",
    "Spotify for learning",
    "Rad stickers with futuristic rainbow shine.",
    "The brand search engine",
    "Make your slides shine with one click ✨",
    "Easily diagram anything, together",
    "Craft stunning Instagram stories, share them everywhere 🚀",
    "Google of domain names",
    "Convert any photo to a duotone in seconds",
    "Tightly curated lists of the best startup tools",
    "Dev community platform",
    "Product hunt but only one featured product a day",
    "Bring Instagram Stories to your website for free 🔥",
    "Converts brand assets to consistent into ads & social images",
    "It's like Scott's Cheap flights, but for Airbnb's.",
    "Search for anything, find a color.",
    "Find brands and influencers that match your style with AI.",
    "Free brand asset management tool for teams",
    "Guests for your next event or podcast - or submit yourself!",
    "Put any form or survey at yoursite.com, and brand it",
    "Free personalized virtual backgrounds for Zoom.",
    "Beautiful free presentation templates for Google Slides",
    "Discover the world’s top designers & creative professionals",
    "Stories for jobs. Because cover letters suck! 🤳✨",
    "Create free style guides in less than 5 minutes",
    "Branded virtual office for your remote team's Zoom meetings.",
    "Get notified when people mention your brand or competitors",
    "Digital business cards and contact manager app",
    "Guides, principles, strategies and tactics for Jr to Sr devs",
    "Score and track audience engagement",
    "The deep learning logo maker",
    "Custom-branded laptop stands",
    "Practical tips on how to elevate video marketing efforts",
    "Mental health support for anyone, anywhere",
    "The premium digital business card",
    "Free landing page for your links, with super powers",
    "Infinitely customizable graphics for everyone",
    "Helping small brands have big conversations",
    "Automatic SSL management solution for SaaS providers",
    "Easily design custom fonts in a few steps",
    "One tap, no app. The smart business card everyone can use.",
    "Create stunning, professional presentations in minutes",
    "Update your product? Update your customers.",
    "Mailchimp for direct mail",
    "World's latest stories in 9-second reads. No BS. No bias.",
    "Discover, create & share digital brand guidelines",
    "The New Way to Play",
    "Add some charm to your life.",
    "Get access to over 150 + new trends every week",
    "Real-time mentions of your startup from social & the web",
    "Online brand book mindset tool for brand creators 💎",
    "Send office exercise tips & inspiring notes to Slack/Teams",
    "Convert existing blog content to video, automagically",
    "A unique way to explore color using lighting and pigment",
    "Find the perfect name for your startup",
    "Collaborate with super freelance designers.",
    "Create and order business cards in minutes",
    "Create Medium-like series, but embed/share them anywhere",
    "Infinite UI designs",
    "Create animated logos in a few clicks",
    "Tons of font ideas in one click",
    "The brand-building platform for emerging businesses.",
    "Free logo designs for your projects, added every week",
    "Try fonts on a live website and share results with a link.",
    "A random generator for design briefs.",
    "Make Google Docs good-looking in two clicks",
    "Create your own podcast intro for free in minutes",
    "An AI-Powered Domain Name Generator",
    "Define your brand voice",
    "DIY kit to help makers' startups get press coverage",
    "Get instant feedback on your LinkedIn profile, powered by AI",
    "A whiteboard for you laptop lid",
    "On-demand jewelry design and manufacturing platform.",
    "Sexy logos for your hot startup",
    "Infinitely customizable icons for everyone.",
    "Create professional logos in minutes on your phone",
    "An all black dot grid notebook for designers & illustrators",
    "Create your own personal website in under 3 minutes",
    "Easy steps for every budget",
    "DIY logo maker, create original logos in seconds",
    "Compare the online awareness of 2 brands in a battle",
    "Free brand art boards for Google Suite",
    "All available Emoji domains in one place",
    "Show your work. Tell your story.",
    "Simple high-quality swag for you or your company",
    "List of resources to buy, learn and acknowledge typography",
    "Engage with website visitors, generate qualified leads ✨",
    "Make Instagram Stories Ads for your brand by Shakr & HubSpot",
    "Custom domains, analytics and SEO metatags for RoamResearch",
    "Analyze any brand online in seconds",
    "Sound activated light up laptop skins with your logo",
    "Online comments aggregated in one dashboard",
    "Thousands of spaces in one coworking membership.",
    "An intelligent business name generator",
    "How to differentiate & position your eCommerce brand",
    "Build Your Audience With Podcasts From WordPress Articles",
    "Put any site behind your custom domain",
    "Grow your Instagram with quality hashtags",
    "The original logos your favourite startups launched with",
    "The platform for online written content 📝",
    "Automated keyword monitoring for Reddit",
    "The world’s best library of free presentation templates.",
    "The deep learning logo maker",
    "The best tools to help you build your startup",
    "The offer management and closing platform for HR teams",
    "Personalized, celebrity video marketing simplified",
    "The most versatile graphic design + creativity tool",
    "Make delicious coffee, anytime. Now More Coffee, Same Price.",
    "Custom virtual Zoom backgrounds to support LGBTQ+ Pride",
    "Design your own tees, totes, temporary tattoos & logos",
    "Custom swag packs, assembled and delivered automatically",
    "Apply complex designs + logos to any surface w/ vinyl decals",
    "Hyper-personalized mobile campaigns, powered by SMS.",
    "Stickers for fans of unix, software, coding and open source",
    "Beautiful NFC business cards that trigger digital actions",
    "All tools to create & check startup names in one place",
    "Unlimited custom illustrations for one flat monthly rate.",
    "If Trello and Slack had a baby - new team collaboration app",
    "Make addictive apps less convenient",
    "A collection of SVG Logos for developers",
    "Create a style guide & integrate with Sketch, Slack, & Gulp",
    "A company name generator that's actually useful",
    "Modern, minimal race track art on wood and metal.",
    "Get feedback for your startup ideas      🔥",
    "Zoom games to play with friends in the time of Corona",
    "The fastest business card experience ever, now with branding",
    "Crowdsourced database of company names & stories",
    "Generates modern startup names based on multiple seed words",
    "A mobile web-page builder.",
    "AI-designed stationary, business cards, and more",
    "Label your products with a premium 'no label' look",
    "Create beautiful landing pages for your mobile apps in secs",
    "Tools and resources for naming things",
    "Give your Substack a proper home at your own domain.",
    "Personal branding theme for developers.",
    "Logo Design Powered by Machine + Human",
    "The Talk Show for Marketers",
    "Create a business name in a few clicks!",
    "Promote your product with postcards",
    "A brand design tool for your whole team",
    "A newsletter about how and why people spend time and money.",
    "https://www.producthunt.com/posts/pagerocket",
    "An end to end design system in Sketch and ReactJS",
    "Your automated podcast producer - edit, brand, publish",
    "A fast, beautiful, professional website for any podcast",
    "The best way to notify users about your product updates",
    "Live-monitor everything that's posted on Reddit & HackerNews",
    "Give your podcasts superpowers",
    "Crowdsource your new company's tagline",
    "A better way to capture, annotate and share screenshots",
    "The fastest, smartest t-shirt ordering system in the world.",
    "Custom domains, branding and analytics for Trello",
    "Websites for content creators",
    "Online mentions relevant to your brand at your fingertips.",
    "DIY logo maker for your next project",
    "Better social media keyword alerts",
    "Social campaign briefs made easy",
    "Make connections, find jobs, and recruit top creative talent",
    "Custom silkscreen and rubber stamp toolkits on the cheap",
    "A high-end stock photography subscription for your brand",
    "Real-world video tutorials & courses for modern designers",
    "Add multiple links to your bio for free",
    "A better way to create design briefs",
    "See if your username is available on 100+ social networks",
    "Custom packaging, made simple. 10 boxes for $10",
    "Create your own Netflix with a few lines of code!",
    "Beautiful announcement pop-ups that convert visitors.",
    "Isomorphic TypeScript client for PostgreSQL with replication",
    "Discover online tools that other startups use",
    "Easiest way to order custom packaging online.",
    "A collection of PH's most popular curated lists.",
    "The community-based video interview platform",
    "Brandable domains, sent right to your inbox",
    "AI powered brand name generator",
    "An all-in-one DIY fundraising solution for launch to exit",
    "Register a new website with one click. Live in 5 mins.",
    "Find out if your startup's name is available on the web!",
    "Hot and ready logos for sale",
    "The app that pays you to play",
    "Print your pet on socks - custom made socks for dog owners",
    "Find companies committed to packaging transparency",
    "T-shirts & posters celebrating the absurdity of startup life",
    "Create custom packaging in 3D and order in low volume",
    "Create a free shareable design brief. No email needed. ",
    "Hot sauce that kicks ass",
    "A powerful new photo editor for iPhone",
    "Step-by-step marketing guide for novice entrepreneurs",
    "A social media tool that lets anyone become an influencer",
    "Landing page UI/UX & graphic design on monthly subscription",
    "Generate your own logo with ease",
    "A front-end url shortener without any database",
    "GIPHY powered sticker functionality for sites everywhere.",
    "🍦 The inside scoop on brandable domains",
    "Beautiful professional webpage with a single click",
    "A landing page for your digital identity",
    "An easy system to mix, match & design a new custom logo",
    "Get paid to post about your favorite brands",
    "Bootstrapped guide to PR, branding, marketing & growth 👀",
    "Create beautiful & unique graphics in minutes",
    "Don’t go brandless during a pandemic.",
    "Supercharge your personal brand 🚀",
    "Generate custom professional packaging templates in seconds.",
    "Your service for custom dashboards.",
    "Spell out the first letter of every emoji: 🐭🐙🐭",
    "The fastest business card experience ever",
    "Domain name ideas delivered daily",
    "Outside stuff for inside people.",
    "Creative platform for professional video branding.",
    "Fastest and easiest way to order custom magnets online",
    "Indoor plants for your home or startup office",
    "13 games for stress tolerance & mindfulness",
    "Learn everything about the organization you're researching.",
    "The world's first marketplace for craft beer brand design",
    "Turn text into animated, social media video ads 📹 ✨",
    "AI logo maker and brand builder",
    "Free, instant, custom-made logos using machine learning",
    "Dynamic personal websites for people who wear multiple hats",
    "Rad patches and pins from amazing illustrators",
    "The Tinder of influencer marketing",
    "Interactive 3d models for drawing reference",
    "Mobile app & design assets for activism.",
    "Essential Figma plugin for simultaneous HSL color adjustment",
    "An immersive journey into what UX is and why it matters.",
    "Create your own parody slogans for \"world-changing\" startups",
    "A zen game with a story told without any dialogue",
    "Easily Sell custom tshirts in your shopify store",
    "Branded packaging accessible to anybody who needs it",
    "Browse recently expired, pronounceable domain names",
    "Launch a big digital footprint in 60 seconds 👣",
    "Providing secure, simple and encrypted video conferencing",
    "Quality custom socks for your company",
    "Create and design your landing, event, business in one page",
    "-",
    "Trigger donations on climate or Covid-19 by taking surveys",
    "User-friendly way to generate profits",
    "Host your brand guidelines and assets in the cloud",
    "Create stunning digital business cards",
    "Boost text, photo, and Instagram reviews with Messenger.",
    "Find an available name for your next brilliant idea",
    "Elevate your cooking",
    "Professional design for your videos, no software required!",
    "Next gen VPN, total browser encryption & decentralized trust",
    "High quality shirts for the daily minimalist.",
    "Design your logo in 2 clicks",
    "Learn new words as you surf the web",
    "Measure your brand performance any way you need to 👋",
    "Automated personalized Thank-You notes for Shopify",
    "Single cup, specialty grade coffee you can take anywhere",
    "Unlimited graphic design at $259 per month",
    "Grow your brand with deep analysis on social media",
    "Collect, curate, and publish authentic customer experiences.",
    "Send personalized direct mail letter campaigns",
    "Just a collection of dumpster-fire, garbage colors.",
    "A tribute to Seth Godin's book recommendations",
    "Don't have a dog? This app let's you play with one!",
    "WordPress to apps. A native news apps platform.",
    "Live slideshow for any occasion",
    "Beautiful gradients as placeholder images  just for you",
    "Tell coffee you need a break. Real milk tea.",
    "Offline-ready webapp for creating flat, Android-style icons.",
    "Create an event app in 3 easy steps under 30 minutes",
    "Purpose driven, micro-communities",
    "Book from a curated collection of great experiences easily",
    "Most creative way to find a catchy name for your new venture",
    "An easy way to market locally with mail",
    "Forget what you know about instant coffee.",
    "Explore the sky in your neighborhood with Foo Fighters",
    "A new, affordable naming startup for startups",
    "Do hassle-free email marketing with this powerful tool 🔥",
    "Digital business cards that are easily shared and searched",
    "Use badges, images or videos with your website's favicon",
    "A blackboard for your laptop lid",
    "Create interactive Facebook live videos in few clicks",
    "An everyday support system for life in the city with dogs.",
    "Mini social networks for all your personas ",
    "Free business card, brochure, posters & packaging mockups",
    "E-book about full creative path to effective branding",
    "Share files the way you'd want to receive them",
    "Empower your customers to represent your true brand.",
    "Generate a name and logo for your hipster business",
    "Protect your images, promote your brand",
    "Access documents most relevant to your current task",
    "Make Safari toolbar more consistent with your brand colors",
    "A hand-picked directory of the Best resources for Startups",
    "Automatic smart web pages - Better stories for your content.",
    "Track and change your mood throughout the day",
    "Get hundreds of slogan ideas for your project or business",
    "Show off your logo design projects",
    "Natural men's hair products in biodegradable containers",
    "Stickers designed to mess with your notification addiction",
    "Tinder for ideas",
    "We replace the business card",
    "Visual collaboration platform for marketing and remote teams",
    "Mac sticker store",
    "Auto create social media posts",
    "Teespring for event decorations and gifts",
    "See Domain Name Search Results As You Type",
    "Swipe through Tinder-for-X ideas",
    "Unique co-branded gifts for companies",
    "On demand packaging boxes with your logo",
    "Better than a greeting card, more personal than flowers.",
    "It's Hip, It's Current, It's Stylish, It's Hipster.",
    "Build your website and connect with the media industry.",
    "One-of-a-kind startup swag",
    "A simple and functional carrying solution.",
    "Discover walks & happiness outdoors",
    "Deep, A.I. 'in-video' analysis & fan video content marketing",
    "Rethink remarketing with relevant product reminders",
    "The fastest way to share yourself.",
    "Free tool to grade your branding in seconds",
    "Digital Tokens for NFL Players",
    "A brand asset manager for your menu bar",
    "Some lovely looking letterpress business cards",
    "Find lit clubs & bars near you",
    "Discover and connect with video influencers for your brand",
    "Build powerful apps faster - without coding",
    "Unsponsored documentary profiles of business and culture",
    "Send stunning flowers from NY's and London's best florists",
    "Search 17 emoji domains for free",
    "Get logos for site/app with this dead-simple HTML API",
    "The Mighty Networks Guide to Building Communities Online",
    "Matching digital & tech professionals to jobs",
    "Design & order promotional items for your company in minutes",
    "Find or offer shelter during emergencies and evacuations 🏠🌀🔥",
    "A do-it-yourself logo builder",
    "Build your brand",
    "Send WhatsApp messages to anyone without saving their number",
    "Advanced social media search. Ultimate social selling tool!",
    "The digital swear jar app",
    "Curated directory of sharing economy resources to save money",
    "Free, human-reviewed logo report cards",
    "Simplest, versatile portfolio website",
    "Nonfiction made Simple",
    "Livestream your Squad and Game!",
    "Generate logos for open-source projects",
    "Taking the hassle out of finding an awesome cleaning service",
    "Embed Reddit comments on your website ",
    "Handwritten direct mail campaigns",
    "Achieve Your Potential!",
    "T-shirts and apparel with ultra-hip sayings 💯 💵 💪 🔥",
    "Company monitoring, customized, curated & delivered anywhere",
    "A Podcast about YouTube culture",
    "The world's simplest DAM system",
    "The first curated GIF keyboard",
    "Largest resource of unique .com domain names.",
    "Source images from 20mm photographers and measure engagement",
    "Turn your blogs into videos with three simple steps",
    "Build your own dynamic brand that generates conversions",
    "A pay-what-you-want crowdsourcing business name service.",
    "Embeddable interactive job ads",
    "How to build a brand",
    "Aim.io: a non-intrusive, most-effective ad network.",
    "Represent multiple projects and companies",
    "Production house. We partner brands with great stories. ",
    "If You Begin, You Win.",
    "A DJ simulator created from an Instagram Stories hack.",
    "Craft your company's story & make your products irresistible",
    "The new paradigm for connecting brands to people",
    "Get tips for staying on top of your resolutions",
    "A chat with Rob Royer / Founder of Interior Define",
    "Fresh website creates more referrals",
    "On Matt Miller's ingenious business & summer vacations!",
    "Net promoter score for some of the biggest businesses",
    "A chat with David Gardner, founder of ColorJar",
    "A powerful, award-winning app for media monitoring  🚀",
    "Strategies for mastering your brand",
    "What does a Brand Manager in CPG do?",
    "The art of hustle and how to break into your dream role",
    "How Patrick coined the term FOMO on the internet!",
    "Top 5 ways to stay the course",
    "Top 5 ways to get someone’s attention without being a pest",
    "The rise of bottoms up sales and branding in SaaS",
    "The power of brands and influencers",
    "Company DNA and creating brands with purpose",
    "Why you must define success before thinking about the tech!",
    "Top 5 signs you need to switch things up w/ Niala Boodhoo",
    "5 Craziest moments in your business owner life",
    "Top 5 scariest things for your business",
    "Food blogger Rachel Matthews shares her best practices",
    "Top 5 ways you're driving YOURSELF crazy - And how to stop",
    "Building a brand and what it's like at Buffer",
    "Behind the scenes of making a promo video",
    "Strategically answering questions on Quora to get more views",
    "Top 5 ways to have more committed and engaged employees",
    "Top 5 ways to tell that the prospect is not that into you",
    "With Vincenzo Landino & Rob Hix",
    "Talk about the importance of targeting and the PAS framework",
    "Designing a brand strategy that scales within a startup",
    "The Ultimate Guide to Building Your Personal Brand",
    "This week we discuss the redesign of RGBA and the new iPhone",
    "Sharing our experiences to find a blog process that works",
    "How to turn your passion into a business",
    "Rajiv Menon on Entrepreneurship",
    "How important is it to define your niche?",
    "Top 5 Reasons Your Labor Costs Are Going UP",
    "Top 5 money mistakes small businesses make",
    "Discussing how websites can be used as marketing tools",
    "Talking about websites helped us improve our websites",
    "Top 5 tools for getting work done ANYWHERE",
    "Carl's path to 20K Youtube subscribers",
    "Conversation centered on not chasing ‘design fame'",
    "How culture and diversity informs design with Hebah",
    "Top 5 emails you are going to write one million times",
    "Top 5 ways to manage your online reputation!",
    "Eric Friedensohn joins us for the Creative South Podcast",
    "Talking about user experience for small business websites",
    "The Top 5 Wardrobe Mistakes Small Business People Make",
    "Discussing 2 ways to build up a website",
    "\"Don't create users, you want to create evangelists.\"",
    "5 spiritual practices you need to survive self-employment",
    "Top 5 things biz owners say that actually mean the opposite",
    "Getting started making video with your phone",
    "The top 5 things to do when you have free time",
    "We cover a quick hack that will increase your revenue fast",
    "Video as a sales tool (The tipping point)",
    "3 action steps to structuring a promo video",
    "A podcast about design, by designers.",
    "Top 5 ways to have better business conversations",
    "Top 5 Ways To Get Value Out Of An Online Community",
    "Choosing form makes you more effective and enjoyable",
    "Top 5 ways to get out more",
    "Top 5 ways to say \"Thank You\" to your team",
    "Tips to create a brand strategy & tell a story effectively",
    "Free review removal chatbot for businesses"
]
