[
  {
    id: 1,
    name: 'Brand Kit by Premast',
    tagline: 'Manage, share and create branded content in PowerPoint',
  },
  {
    id: 2,
    name: 'Namify',
    tagline: 'Meaningful brand names, free logo, social & domain check',
  },
  {
    id: 3,
    name: 'Boring Avatars',
    tagline: 'JavaScript library to generate SVG avatars based on text',
  },
  {
    id: 4,
    name: 'Be.Live',
    tagline: 'Live streaming app to make the whole world your studio',
  },
  {
    id: 5,
    name: 'Premast',
    tagline: 'Create presentations like never before',
  },
  {
    id: 6,
    name: 'Good Landing Page',
    tagline: 'Curation of 300+ best landing pages for design inspiration',
  },
  {
    id: 7,
    name: 'LinkMngr',
    tagline: 'A complete link management and tracking solution',
  },
  {
    id: 8,
    name: 'Evolve',
    tagline: 'Connect your card and earn up to 15% automatic cash back',
  },
  {id: 9, name: 'Ctiny', tagline: 'Short link, More control'},
  {
    id: 10,
    name: 'chaosMachine',
    tagline: 'One-click unique graphics generator',
  },
  {id: 11, name: 'BrandBird', tagline: 'Brand your Twitter content uniquely'},
  {
    id: 12,
    name: 'How to NFT',
    tagline: 'Free resource for providing creators access to NFT',
  },
  {id: 13, name: 'Sites', tagline: 'No-code website building platform'},
  {
    id: 14,
    name: 'Headers.me',
    tagline: 'Create social cover images that get you followers',
  },
  {
    id: 15,
    name: 'CopyAim',
    tagline: 'AI copywriting & brainstorming for instant marketing copy',
  },
  {
    id: 16,
    name: 'Business Name Generator by Looka',
    tagline: 'Generate names, check availability, and see logo ideas',
  },
  {
    id: 17,
    name: 'PFPMaker',
    tagline: 'Create an awesome profile pic from any photo',
  },
  {id: 18, name: 'Alter', tagline: 'Business name marketplace'},
  {
    id: 19,
    name: 'Swag Fair',
    tagline: 'Sustainable swag made by small businesses',
  },
  {
    id: 20,
    name: 'BizCard',
    tagline: 'Design smart & affordable paperless business cards',
  },
  {
    id: 21,
    name: 'Video Donut',
    tagline: 'Nail the welcome to your site with a stories-style video!',
  },
  {
    id: 22,
    name: 'Eureka Surveys',
    tagline: 'Survey over 1 million people within minutes',
  },
  {
    id: 23,
    name: 'Core Studio° by Corebook.io',
    tagline: 'Online brand guidelines prototyping platform',
  },
  {
    id: 24,
    name: 'Mentioned',
    tagline: 'Get an email when your website is posted online.',
  },
  {
    id: 25,
    name: 'Pitch Deck Template for 2021',
    tagline: '100+ investor approved slides for your pitch deck',
  },
  {
    id: 26,
    name: 'Namejax',
    tagline: 'Curated brand marketplace for your next product',
  },
  {
    id: 27,
    name: 'Startup Stash',
    tagline: 'A curated directory of 400 resources & tools for startups',
  },
  {
    id: 28,
    name: 'Vidiwise',
    tagline: "1-click video calls based on your visitor's journey, free",
  },
  {
    id: 29,
    name: 'Domain Point',
    tagline: 'Never pay for a premium domain again.',
  },
  {id: 30, name: 'QR Menu Creator', tagline: 'Make a QR Code Menu for FREE'},
  {
    id: 31,
    name: 'Bybrand - Create from scratch',
    tagline: 'Create an HTML email signature from scratch',
  },
  {id: 32, name: 'Booklets.io', tagline: 'Bite sized learning for creatives'},
  {id: 33, name: '1Brand', tagline: 'Custom brand guidelines in moments'},
  {
    id: 34,
    name: 'Figma Pitch Deck Template',
    tagline: 'The easiest way to build a compelling pitch deck in Figma',
  },
  {id: 35, name: 'NameSnack', tagline: 'Free business name generator'},
  {
    id: 36,
    name: 'Pizzly',
    tagline: 'Building API integrations has never been easier',
  },
  {
    id: 37,
    name: 'PodBooker',
    tagline: 'The easiest way to get booked on podcasts',
  },
  {
    id: 38,
    name: 'First Search',
    tagline: "The world's best startup advice, curated and searchable.",
  },
  {
    id: 39,
    name: 'One Word Domains',
    tagline: 'Database of 700K+ available and brandable one-word domains',
  },
  {
    id: 40,
    name: 'SaaS Pages',
    tagline: '900+ Screenshots of the best SaaS landing pages',
  },
  {id: 41, name: 'Mailbum', tagline: 'Email signatures without the fuss'},
  {
    id: 42,
    name: 'Carrd',
    tagline: 'Simple, responsive, one-page sites for pretty much anything.',
  },
  {
    id: 43,
    name: 'DrawKit',
    tagline: 'MIT licensed SVG illustrations, in 2 styles',
  },
  {
    id: 44,
    name: 'LT Fan Platform',
    tagline: 'Blockchain fan engagement software for sports brands',
  },
  {
    id: 45,
    name: 'Fiverr Logo Maker',
    tagline: 'The first logo maker that is powered by actual designers',
  },
  {
    id: 46,
    name: 'Brandmo',
    tagline: 'Find the perfect brand name for any project',
  },
  {id: 47, name: 'One Profile', tagline: 'Discontinued'},
  {id: 48, name: 'Niice 3.0', tagline: 'Netflix for your brand assets'},
  {
    id: 49,
    name: 'Startup Launch List',
    tagline: 'A​rticles you need to read before launching a startup.',
  },
  {
    id: 50,
    name: 'Artboard Studio',
    tagline: 'Online graphic design app mainly focused on product mockups.',
  },
  {
    id: 51,
    name: 'Screen Recorder - Snipclip',
    tagline: 'A minimal, ad-free screen recorder in your browser',
  },
  {
    id: 52,
    name: 'Roadmap v.1.0',
    tagline: 'Radically transparent project & team management app.',
  },
  {
    id: 53,
    name: 'Javelin by Lean Startup Machine',
    tagline: 'All-in-one platform for building products people want',
  },
  {
    id: 54,
    name: 'Google Workspace',
    tagline: 'Gmail, Calendar, Drive, Docs, Sheets, Slides, Meet',
  },
  {id: 55, name: 'Mobilo Wood', tagline: 'Smart business card made of wood'},
  {
    id: 56,
    name: 'Popl',
    tagline: 'Share your digital business card with a tap',
  },
  {
    id: 57,
    name: 'Zest',
    tagline: 'Collect feedback recordings from your users',
  },
  {id: 58, name: 'Wavium 2.0', tagline: 'Your always up-to-date personal page'},
  {
    id: 59,
    name: 'Visably',
    tagline: 'Measure and improve your brand visibility in search.',
  },
  {
    id: 60,
    name: 'Landing Pages in MailChimp',
    tagline: 'Easy to build, custom landing pages for free',
  },
  {
    id: 61,
    name: 'linkish',
    tagline: 'Turn boring bookmarks into embedded audio & video cards',
  },
  {
    id: 62,
    name: 'Atomize React',
    tagline: 'An open source design system for ReactJS',
  },
  {
    id: 63,
    name: 'Artboard Studio 2.0',
    tagline: 'Design, collaborate and present all in the browser',
  },
  {
    id: 64,
    name: 'Websites by MailerLite',
    tagline: 'Create a website in 1 day! Free no-code, drag & drop builder',
  },
  {
    id: 65,
    name: 'Huddle',
    tagline: 'Get a pop-up team of expert designers and builders.',
  },
  {
    id: 66,
    name: 'Brandful',
    tagline: 'Ready-made brands, crowd-sourced for your next startup',
  },
  {id: 67, name: 'Make My Persona', tagline: 'A free buyer persona generator'},
  {
    id: 68,
    name: 'Premast Plus',
    tagline: 'Access tons of design elements inside your PowerPoint',
  },
  {
    id: 69,
    name: 'Logo Design for Indie Makers',
    tagline: 'A guide to create a great logo in 30 minutes or less 👩🏻‍🎨',
  },
  {id: 70, name: 'Namelix', tagline: 'AI business name generator'},
  {id: 71, name: 'Looka (formerly Logojoy)', tagline: 'AI-powered logo maker'},
  {
    id: 72,
    name: 'WEBM To MP4',
    tagline: 'Convert .webm files to .mp4 files without uploading them',
  },
  {
    id: 73,
    name: 'Vectornator Pro For Mac',
    tagline: 'Vector graphic design software for macOS Catalina',
  },
  {
    id: 74,
    name: 'Evolt Design Suite',
    tagline: 'The design thinking suite to create great user experiences',
  },
  {
    id: 75,
    name: 'Welder',
    tagline: 'Record HQ content (podcast, etc..) for your startup remotely',
  },
  {
    id: 76,
    name: 'Christmas Design Kit',
    tagline: '176 Figma Design Templates for startups',
  },
  {
    id: 77,
    name: 'Freebie.Supply',
    tagline: 'Awesome free things for entrepreneurs & startups',
  },
  {
    id: 78,
    name: 'SaaS Startup Guide by Hotjar 🔥',
    tagline: 'You have an MVP. Now what?',
  },
  {id: 79, name: 'Urlefy', tagline: 'URL shortener to monitor your business'},
  {id: 80, name: 'Pexels Videos 3.0', tagline: 'Free videos for everyone.'},
  {
    id: 81,
    name: 'Unsplash for iOS',
    tagline: 'High-res photos you can use freely for anything on iOS.',
  },
  {id: 82, name: 'Emblem', tagline: 'Build your own beautiful brand'},
  {
    id: 83,
    name: 'Zoom Background Generator',
    tagline: 'Get a professional branded Zoom background in two clicks',
  },
  {
    id: 84,
    name: 'Mupixa 2.0',
    tagline: 'Remote usability testing, eye tracking, heatmaps, replays',
  },
  {
    id: 85,
    name: 'UI Jar',
    tagline: 'Hand-picked design inspiration for your real life projects',
  },
  {
    id: 86,
    name: 'Resoundly',
    tagline: 'Start a podcast without recording a thing',
  },
  {id: 87, name: 'Knowable Memberships', tagline: 'Spotify for learning'},
  {
    id: 88,
    name: 'Holographic Stickers by Sticker Mule',
    tagline: 'Rad stickers with futuristic rainbow shine.',
  },
  {id: 89, name: 'Brandfetch', tagline: 'The brand search engine'},
  {
    id: 90,
    name: 'DeckRobot for PowerPoint',
    tagline: 'Make your slides shine with one click ✨',
  },
  {id: 91, name: 'Plectica', tagline: 'Easily diagram anything, together'},
  {
    id: 92,
    name: 'Fastory',
    tagline: 'Craft stunning Instagram stories, share them everywhere 🚀',
  },
  {id: 93, name: 'Dofo.com', tagline: 'Google of domain names'},
  {
    id: 94,
    name: 'Duotone',
    tagline: 'Convert any photo to a duotone in seconds',
  },
  {
    id: 95,
    name: 'StartupResources.io',
    tagline: 'Tightly curated lists of the best startup tools',
  },
  {id: 96, name: 'Indians Who Code', tagline: 'Dev community platform'},
  {
    id: 97,
    name: 'Just Launched',
    tagline: 'Product hunt but only one featured product a day',
  },
  {
    id: 98,
    name: 'Instagram Stories Widget - by Fastory',
    tagline: 'Bring Instagram Stories to your website for free 🔥',
  },
  {
    id: 99,
    name: 'RelayThat',
    tagline: 'Converts brand assets to consistent into ads & social images',
  },
  {
    id: 100,
    name: 'Sponstayneous',
    tagline: "It's like Scott's Cheap flights, but for Airbnb's.",
  },
  {
    id: 101,
    name: 'Figma Color Search',
    tagline: 'Search for anything, find a color.',
  },
  {
    id: 102,
    name: 'Influencer Sphere',
    tagline: 'Find brands and influencers that match your style with AI.',
  },
  {
    id: 103,
    name: 'Brandy',
    tagline: 'Free brand asset management tool for teams',
  },
  {
    id: 104,
    name: 'Speaker Directory by HeySummit',
    tagline: 'Guests for your next event or podcast - or submit yourself!',
  },
  {
    id: 105,
    name: 'AnyForm',
    tagline: 'Put any form or survey at yoursite.com, and brand it',
  },
  {
    id: 106,
    name: 'HiHello Backgrounds for Zoom',
    tagline: 'Free personalized virtual backgrounds for Zoom.',
  },
  {
    id: 107,
    name: 'SlidesPPT',
    tagline: 'Beautiful free presentation templates for Google Slides',
  },
  {
    id: 108,
    name: 'A brand new Dribbble',
    tagline: 'Discover the world’s top designers & creative professionals',
  },
  {
    id: 109,
    name: 'HEROES JOBS',
    tagline: 'Stories for jobs. Because cover letters suck! 🤳✨',
  },
  {
    id: 110,
    name: 'Frontify',
    tagline: 'Create free style guides in less than 5 minutes',
  },
  {
    id: 111,
    name: 'VirtualOffice for Zoom',
    tagline: "Branded virtual office for your remote team's Zoom meetings.",
  },
  {
    id: 112,
    name: 'BrandMentions 2.0',
    tagline: 'Get notified when people mention your brand or competitors',
  },
  {
    id: 113,
    name: 'Nexus',
    tagline: 'Digital business cards and contact manager app',
  },
  {
    id: 114,
    name: 'The Coding Career Handbook',
    tagline: 'Guides, principles, strategies and tactics for Jr to Sr devs',
  },
  {
    id: 115,
    name: 'APEX Scoring System',
    tagline: 'Score and track audience engagement',
  },
  {id: 116, name: 'Brandmark V2', tagline: 'The deep learning logo maker'},
  {id: 117, name: 'OpenStanding', tagline: 'Custom-branded laptop stands'},
  {
    id: 118,
    name: 'Guide to Video Marketing by Wistia',
    tagline: 'Practical tips on how to elevate video marketing efforts',
  },
  {
    id: 119,
    name: 'LetsConnect',
    tagline: 'Mental health support for anyone, anywhere',
  },
  {
    id: 120,
    name: 'Mobilo Metal Card',
    tagline: 'The premium digital business card',
  },
  {
    id: 121,
    name: 'Liinks',
    tagline: 'Free landing page for your links, with super powers',
  },
  {
    id: 122,
    name: 'illustrio',
    tagline: 'Infinitely customizable graphics for everyone',
  },
  {
    id: 123,
    name: 'Thea',
    tagline: 'Helping small brands have big conversations',
  },
  {
    id: 124,
    name: 'Kilo SSL',
    tagline: 'Automatic SSL management solution for SaaS providers',
  },
  {
    id: 125,
    name: 'Unique',
    tagline: 'Easily design custom fonts in a few steps',
  },
  {
    id: 126,
    name: 'Cardanti Smart Business Card',
    tagline: 'One tap, no app. The smart business card everyone can use.',
  },
  {
    id: 127,
    name: 'Slidebean 3.0',
    tagline: 'Create stunning, professional presentations in minutes',
  },
  {
    id: 128,
    name: 'ReleaseNotes',
    tagline: 'Update your product? Update your customers.',
  },
  {id: 129, name: 'Mailjoy', tagline: 'Mailchimp for direct mail'},
  {
    id: 130,
    name: 'Volv',
    tagline: "World's latest stories in 9-second reads. No BS. No bias.",
  },
  {
    id: 131,
    name: 'Patomic',
    tagline: 'Discover, create & share digital brand guidelines',
  },
  {id: 132, name: 'Playground', tagline: 'The New Way to Play'},
  {
    id: 133,
    name: 'Acrylic Charms by Sticker Mule',
    tagline: 'Add some charm to your life.',
  },
  {
    id: 134,
    name: 'Trend Watchers',
    tagline: 'Get access to over 150 + new trends every week',
  },
  {
    id: 135,
    name: 'Awario',
    tagline: 'Real-time mentions of your startup from social & the web',
  },
  {
    id: 136,
    name: 'Corebook.io',
    tagline: 'Online brand book mindset tool for brand creators 💎',
  },
  {
    id: 137,
    name: 'Daily Say',
    tagline: 'Send office exercise tips & inspiring notes to Slack/Teams',
  },
  {
    id: 138,
    name: 'Automagical',
    tagline: 'Convert existing blog content to video, automagically',
  },
  {
    id: 139,
    name: 'Pigment',
    tagline: 'A unique way to explore color using lighting and pigment',
  },
  {
    id: 140,
    name: 'Namefruits',
    tagline: 'Find the perfect name for your startup',
  },
  {
    id: 141,
    name: 'Supercreative Profiles',
    tagline: 'Collaborate with super freelance designers.',
  },
  {
    id: 142,
    name: 'Namecheap Business Card Maker',
    tagline: 'Create and order business cards in minutes',
  },
  {
    id: 143,
    name: 'Try Cereals',
    tagline: 'Create Medium-like series, but embed/share them anywhere',
  },
  {id: 144, name: 'Uibot', tagline: 'Infinite UI designs'},
  {
    id: 145,
    name: 'Animated Logos by Placeit',
    tagline: 'Create animated logos in a few clicks',
  },
  {id: 146, name: 'Font Generator', tagline: 'Tons of font ideas in one click'},
  {
    id: 147,
    name: 'ZeBrand',
    tagline: 'The brand-building platform for emerging businesses.',
  },
  {
    id: 148,
    name: 'Logo Dust',
    tagline: 'Free logo designs for your projects, added every week',
  },
  {
    id: 149,
    name: 'Font Fit',
    tagline: 'Try fonts on a live website and share results with a link.',
  },
  {
    id: 150,
    name: 'GoodBrief',
    tagline: 'A random generator for design briefs.',
  },
  {
    id: 151,
    name: 'Google Doc Publisher',
    tagline: 'Make Google Docs good-looking in two clicks',
  },
  {
    id: 152,
    name: 'BuildBubbles',
    tagline: 'Create your own podcast intro for free in minutes',
  },
  {id: 153, name: 'DeepNamer', tagline: 'An AI-Powered Domain Name Generator'},
  {id: 154, name: 'How to Brand You', tagline: 'Define your brand voice'},
  {
    id: 155,
    name: 'Jona',
    tagline: "DIY kit to help makers' startups get press coverage",
  },
  {
    id: 156,
    name: 'LinkedIn Review 2.0',
    tagline: 'Get instant feedback on your LinkedIn profile, powered by AI',
  },
  {id: 157, name: 'DrawAttention', tagline: 'A whiteboard for you laptop lid'},
  {
    id: 158,
    name: 'Gildform',
    tagline: 'On-demand jewelry design and manufacturing platform.',
  },
  {id: 159, name: 'logos.porn', tagline: 'Sexy logos for your hot startup'},
  {
    id: 160,
    name: 'illustrio 2.0',
    tagline: 'Infinitely customizable icons for everyone.',
  },
  {
    id: 161,
    name: 'Logo Foundry',
    tagline: 'Create professional logos in minutes on your phone',
  },
  {
    id: 162,
    name: 'Dot Grid Notebook Black Edition',
    tagline: 'An all black dot grid notebook for designers & illustrators',
  },
  {
    id: 163,
    name: 'Somebody.io',
    tagline: 'Create your own personal website in under 3 minutes',
  },
  {
    id: 164,
    name: 'Brand Building Guides & Tools',
    tagline: 'Easy steps for every budget',
  },
  {
    id: 165,
    name: 'Shopify Hatchful',
    tagline: 'DIY logo maker, create original logos in seconds',
  },
  {
    id: 166,
    name: 'Battle of the Brands',
    tagline: 'Compare the online awareness of 2 brands in a battle',
  },
  {id: 167, name: 'Pilcro', tagline: 'Free brand art boards for Google Suite'},
  {id: 168, name: '😁.to', tagline: 'All available Emoji domains in one place'},
  {id: 169, name: 'Mural', tagline: 'Show your work. Tell your story.'},
  {
    id: 170,
    name: 'Teespring Direct',
    tagline: 'Simple high-quality swag for you or your company',
  },
  {
    id: 171,
    name: 'Typography Resources',
    tagline: 'List of resources to buy, learn and acknowledge typography',
  },
  {
    id: 172,
    name: 'Chatterbot',
    tagline: 'Engage with website visitors, generate qualified leads ✨',
  },
  {
    id: 173,
    name: 'StoriesAds.com',
    tagline: 'Make Instagram Stories Ads for your brand by Shakr & HubSpot',
  },
  {
    id: 174,
    name: 'Roameo',
    tagline: 'Custom domains, analytics and SEO metatags for RoamResearch',
  },
  {
    id: 175,
    name: 'The Brand Grader',
    tagline: 'Analyze any brand online in seconds',
  },
  {
    id: 176,
    name: 'Stickerlight',
    tagline: 'Sound activated light up laptop skins with your logo',
  },
  {
    id: 177,
    name: 'Coment',
    tagline: 'Online comments aggregated in one dashboard',
  },
  {
    id: 178,
    name: 'Global Pass (by Coworker.com)',
    tagline: 'Thousands of spaces in one coworking membership.',
  },
  {
    id: 179,
    name: 'NameBounce',
    tagline: 'An intelligent business name generator',
  },
  {
    id: 180,
    name: '12 Ways To Stay Ahead Of The Competition',
    tagline: 'How to differentiate & position your eCommerce brand',
  },
  {
    id: 181,
    name: 'BuildBubbles',
    tagline: 'Build Your Audience With Podcasts From WordPress Articles',
  },
  {
    id: 182,
    name: 'customDomainer',
    tagline: 'Put any site behind your custom domain',
  },
  {
    id: 183,
    name: 'Flick',
    tagline: 'Grow your Instagram with quality hashtags',
  },
  {
    id: 184,
    name: 'Startup Logo Archive',
    tagline: 'The original logos your favourite startups launched with',
  },
  {
    id: 185,
    name: 'Readory',
    tagline: 'The platform for online written content 📝',
  },
  {
    id: 186,
    name: 'Notifier for Reddit',
    tagline: 'Automated keyword monitoring for Reddit',
  },
  {
    id: 187,
    name: 'Templates by 24Slides',
    tagline: 'The world’s best library of free presentation templates.',
  },
  {id: 188, name: 'Brandmark', tagline: 'The deep learning logo maker'},
  {
    id: 189,
    name: 'Open Strategy',
    tagline: 'The best tools to help you build your startup',
  },
  {
    id: 190,
    name: 'Welcome',
    tagline: 'The offer management and closing platform for HR teams',
  },
  {
    id: 191,
    name: 'Megabiz',
    tagline: 'Personalized, celebrity video marketing simplified',
  },
  {
    id: 192,
    name: 'CREATE 5.0',
    tagline: 'The most versatile graphic design + creativity tool',
  },
  {
    id: 193,
    name: 'Dripkit Coffee 2.0',
    tagline: 'Make delicious coffee, anytime. Now More Coffee, Same Price.',
  },
  {
    id: 194,
    name: 'HavePride.in',
    tagline: 'Custom virtual Zoom backgrounds to support LGBTQ+ Pride',
  },
  {
    id: 195,
    name: 'Makr',
    tagline: 'Design your own tees, totes, temporary tattoos & logos',
  },
  {
    id: 196,
    name: 'Packs by StartupThreads',
    tagline: 'Custom swag packs, assembled and delivered automatically',
  },
  {
    id: 197,
    name: 'Sticker Mule Transfer Stickers',
    tagline: 'Apply complex designs + logos to any surface w/ vinyl decals',
  },
  {
    id: 198,
    name: 'Mobiz',
    tagline: 'Hyper-personalized mobile campaigns, powered by SMS.',
  },
  {
    id: 199,
    name: 'Unixstickers by Sticker Mule',
    tagline: 'Stickers for fans of unix, software, coding and open source',
  },
  {
    id: 200,
    name: 'MOO Business Cards+',
    tagline: 'Beautiful NFC business cards that trigger digital actions',
  },
  {
    id: 201,
    name: 'NameRobot Toolbox',
    tagline: 'All tools to create & check startup names in one place',
  },
  {
    id: 202,
    name: 'Custom Illustrations by Design Pickle',
    tagline: 'Unlimited custom illustrations for one flat monthly rate.',
  },
  {
    id: 203,
    name: 'HeySpace',
    tagline: 'If Trello and Slack had a baby - new team collaboration app',
  },
  {
    id: 204,
    name: 'Stop Wasting Time',
    tagline: 'Make addictive apps less convenient',
  },
  {
    id: 205,
    name: 'SVG Porn',
    tagline: 'A collection of SVG Logos for developers',
  },
  {
    id: 206,
    name: 'Brand.ai',
    tagline: 'Create a style guide & integrate with Sketch, Slack, & Gulp',
  },
  {
    id: 207,
    name: 'Naminum',
    tagline: "A company name generator that's actually useful",
  },
  {
    id: 208,
    name: 'Standing Start Co.',
    tagline: 'Modern, minimal race track art on wood and metal.',
  },
  {
    id: 209,
    name: 'Seedproof',
    tagline: 'Get feedback for your startup ideas 🔥',
  },
  {
    id: 210,
    name: 'Rona Games',
    tagline: 'Zoom games to play with friends in the time of Corona',
  },
  {
    id: 211,
    name: 'Cardify Essential',
    tagline: 'The fastest business card experience ever, now with branding',
  },
  {
    id: 212,
    name: 'Gloatt',
    tagline: 'Crowdsourced database of company names & stories',
  },
  {
    id: 213,
    name: 'namewhale',
    tagline: 'Generates modern startup names based on multiple seed words',
  },
  {id: 214, name: 'Enchᵅ', tagline: 'A mobile web-page builder.'},
  {
    id: 215,
    name: 'Oqtor',
    tagline: 'AI-designed stationary, business cards, and more',
  },
  {
    id: 216,
    name: 'Clear labels by Sticker Mule',
    tagline: "Label your products with a premium 'no label' look",
  },
  {
    id: 217,
    name: 'AppLandr 2.0',
    tagline: 'Create beautiful landing pages for your mobile apps in secs',
  },
  {id: 218, name: 'Onym', tagline: 'Tools and resources for naming things'},
  {
    id: 219,
    name: 'Snorkel for Substack',
    tagline: 'Give your Substack a proper home at your own domain.',
  },
  {id: 220, name: 'Intro', tagline: 'Personal branding theme for developers.'},
  {
    id: 221,
    name: 'Hatchful by Shopify',
    tagline: 'Logo Design Powered by Machine + Human',
  },
  {
    id: 222,
    name: 'Brandwagon by Wistia',
    tagline: 'The Talk Show for Marketers',
  },
  {
    id: 223,
    name: 'Logaster Company Name Generator',
    tagline: 'Create a business name in a few clicks!',
  },
  {id: 224, name: 'Scout', tagline: 'Promote your product with postcards'},
  {
    id: 225,
    name: 'Visage 4.0',
    tagline: 'A brand design tool for your whole team',
  },
  {
    id: 226,
    name: 'The New Consumer',
    tagline: 'A newsletter about how and why people spend time and money.',
  },
  {
    id: 227,
    name: 'PageRocket',
    tagline: 'https://www.producthunt.com/posts/pagerocket',
  },
  {
    id: 228,
    name: 'Straple',
    tagline: 'An end to end design system in Sketch and ReactJS',
  },
  {
    id: 229,
    name: 'Alitu',
    tagline: 'Your automated podcast producer - edit, brand, publish',
  },
  {
    id: 230,
    name: 'Podsites',
    tagline: 'A fast, beautiful, professional website for any podcast',
  },
  {
    id: 231,
    name: 'Beamer',
    tagline: 'The best way to notify users about your product updates',
  },
  {
    id: 232,
    name: 'Alertcamp',
    tagline: "Live-monitor everything that's posted on Reddit & HackerNews",
  },
  {id: 233, name: 'Podcasts Makers', tagline: 'Give your podcasts superpowers'},
  {
    id: 234,
    name: 'OneLiners.co',
    tagline: "Crowdsource your new company's tagline",
  },
  {
    id: 235,
    name: 'ScreenTray',
    tagline: 'A better way to capture, annotate and share screenshots',
  },
  {
    id: 236,
    name: 'Ramp T-shirts',
    tagline: 'The fastest, smartest t-shirt ordering system in the world.',
  },
  {
    id: 237,
    name: 'TrelloMask',
    tagline: 'Custom domains, branding and analytics for Trello',
  },
  {
    id: 238,
    name: 'Streamlabs Creator Sites',
    tagline: 'Websites for content creators',
  },
  {
    id: 239,
    name: 'Brand24 Mobile App 2.0',
    tagline: 'Online mentions relevant to your brand at your fingertips.',
  },
  {
    id: 240,
    name: 'Logomaster.ai',
    tagline: 'DIY logo maker for your next project',
  },
  {id: 241, name: 'Syften', tagline: 'Better social media keyword alerts'},
  {id: 242, name: 'Holo', tagline: 'Social campaign briefs made easy'},
  {
    id: 243,
    name: 'Mixer',
    tagline: 'Make connections, find jobs, and recruit top creative talent',
  },
  {
    id: 244,
    name: 'Lumi',
    tagline: 'Custom silkscreen and rubber stamp toolkits on the cheap',
  },
  {
    id: 245,
    name: 'We Are The Luminous',
    tagline: 'A high-end stock photography subscription for your brand',
  },
  {
    id: 246,
    name: 'Affinicasts',
    tagline: 'Real-world video tutorials & courses for modern designers',
  },
  {id: 247, name: 'Linkie', tagline: 'Add multiple links to your bio for free'},
  {
    id: 248,
    name: 'HolaBrief Beta',
    tagline: 'A better way to create design briefs',
  },
  {
    id: 249,
    name: 'NameChk',
    tagline: 'See if your username is available on 100+ social networks',
  },
  {
    id: 250,
    name: 'Pakible',
    tagline: 'Custom packaging, made simple. 10 boxes for $10',
  },
  {
    id: 251,
    name: 'api.video',
    tagline: 'Create your own Netflix with a few lines of code!',
  },
  {
    id: 252,
    name: 'Content Showcase',
    tagline: 'Beautiful announcement pop-ups that convert visitors.',
  },
  {
    id: 253,
    name: 'Prostgles',
    tagline: 'Isomorphic TypeScript client for PostgreSQL with replication',
  },
  {
    id: 254,
    name: 'Toolbird',
    tagline: 'Discover online tools that other startups use',
  },
  {
    id: 255,
    name: 'Arka',
    tagline: 'Easiest way to order custom packaging online.',
  },
  {
    id: 256,
    name: 'The Stacks',
    tagline: "A collection of PH's most popular curated lists.",
  },
  {
    id: 257,
    name: 'LAMA',
    tagline: 'The community-based video interview platform',
  },
  {
    id: 258,
    name: 'Name2Inbox',
    tagline: 'Brandable domains, sent right to your inbox',
  },
  {id: 259, name: 'Ask Billie', tagline: 'AI powered brand name generator'},
  {
    id: 260,
    name: "Venture360's Startup Fundraising Tool",
    tagline: 'An all-in-one DIY fundraising solution for launch to exit',
  },
  {
    id: 261,
    name: 'Picnic',
    tagline: 'Register a new website with one click. Live in 5 mins.',
  },
  {
    id: 262,
    name: 'Startup Validator',
    tagline: "Find out if your startup's name is available on the web!",
  },
  {id: 263, name: 'Logo Pizza', tagline: 'Hot and ready logos for sale'},
  {id: 264, name: 'Perksy', tagline: 'The app that pays you to play'},
  {
    id: 265,
    name: "Dogs'n'Sox",
    tagline: 'Print your pet on socks - custom made socks for dog owners',
  },
  {
    id: 266,
    name: 'Slash Packaging',
    tagline: 'Find companies committed to packaging transparency',
  },
  {
    id: 267,
    name: 'StartupDrugz',
    tagline: 'T-shirts & posters celebrating the absurdity of startup life',
  },
  {
    id: 268,
    name: 'PackMojo',
    tagline: 'Create custom packaging in 3D and order in low volume',
  },
  {
    id: 269,
    name: 'Create Brief',
    tagline: 'Create a free shareable design brief. No email needed. ',
  },
  {
    id: 270,
    name: 'Mule Sauce by Sticker Mule',
    tagline: 'Hot sauce that kicks ass',
  },
  {id: 271, name: 'Priime', tagline: 'A powerful new photo editor for iPhone'},
  {
    id: 272,
    name: 'Growth Hack Your Startup From 0 to 10k Users In A Month',
    tagline: 'Step-by-step marketing guide for novice entrepreneurs',
  },
  {
    id: 273,
    name: 'Wibber',
    tagline: 'A social media tool that lets anyone become an influencer',
  },
  {
    id: 274,
    name: 'Draftss 2.0',
    tagline: 'Landing page UI/UX & graphic design on monthly subscription',
  },
  {id: 275, name: 'Lapparatus', tagline: 'Generate your own logo with ease'},
  {
    id: 276,
    name: 'Chhota',
    tagline: 'A front-end url shortener without any database',
  },
  {
    id: 277,
    name: 'GIPHY Sticker Embed',
    tagline: 'GIPHY powered sticker functionality for sites everywhere.',
  },
  {
    id: 278,
    name: 'Scooped',
    tagline: '🍦 The inside scoop on brandable domains',
  },
  {
    id: 279,
    name: 'WiseIntro',
    tagline: 'Beautiful professional webpage with a single click',
  },
  {
    id: 280,
    name: 'Rebout.me',
    tagline: 'A landing page for your digital identity',
  },
  {
    id: 281,
    name: 'Envato Logo Kit',
    tagline: 'An easy system to mix, match & design a new custom logo',
  },
  {
    id: 282,
    name: 'Plugg',
    tagline: 'Get paid to post about your favorite brands',
  },
  {
    id: 283,
    name: 'GET ATTENTION',
    tagline: 'Bootstrapped guide to PR, branding, marketing & growth 👀',
  },
  {
    id: 284,
    name: 'Pixelixe',
    tagline: 'Create beautiful & unique graphics in minutes',
  },
  {
    id: 285,
    name: 'Zoom Background Builder',
    tagline: 'Don’t go brandless during a pandemic.',
  },
  {id: 286, name: 'Brandie', tagline: 'Supercharge your personal brand 🚀'},
  {
    id: 287,
    name: 'Die Cut Templates',
    tagline: 'Generate custom professional packaging templates in seconds.',
  },
  {
    id: 288,
    name: 'CentralBoard',
    tagline: 'Your service for custom dashboards.',
  },
  {
    id: 289,
    name: 'MojiLang',
    tagline: 'Spell out the first letter of every emoji: 🐭🐙🐭',
  },
  {
    id: 290,
    name: 'Cardify',
    tagline: 'The fastest business card experience ever',
  },
  {id: 291, name: 'Blipbrands', tagline: 'Domain name ideas delivered daily'},
  {
    id: 292,
    name: 'Advencher Supply Co.',
    tagline: 'Outside stuff for inside people.',
  },
  {
    id: 293,
    name: 'Videobolt 3.0',
    tagline: 'Creative platform for professional video branding.',
  },
  {
    id: 294,
    name: 'Custom Magnets by Sticker Mule',
    tagline: 'Fastest and easiest way to order custom magnets online',
  },
  {
    id: 295,
    name: 'Leon & George',
    tagline: 'Indoor plants for your home or startup office',
  },
  {
    id: 296,
    name: 'Skills',
    tagline: '13 games for stress tolerance & mindfulness',
  },
  {
    id: 297,
    name: 'FindTheCompany',
    tagline: "Learn everything about the organization you're researching.",
  },
  {
    id: 298,
    name: 'Beer Prints',
    tagline: "The world's first marketplace for craft beer brand design",
  },
  {
    id: 299,
    name: 'Yala',
    tagline: 'Turn text into animated, social media video ads 📹 ✨',
  },
  {id: 300, name: 'Tailor Brands', tagline: 'AI logo maker and brand builder'},
  {
    id: 301,
    name: 'Design Rails',
    tagline: 'Free, instant, custom-made logos using machine learning',
  },
  {
    id: 302,
    name: 'Mural Collections',
    tagline: 'Dynamic personal websites for people who wear multiple hats',
  },
  {
    id: 303,
    name: 'Super Team Deluxe',
    tagline: 'Rad patches and pins from amazing illustrators',
  },
  {id: 304, name: 'Collabor8', tagline: 'The Tinder of influencer marketing'},
  {
    id: 305,
    name: 'JustSketchMe',
    tagline: 'Interactive 3d models for drawing reference',
  },
  {
    id: 306,
    name: 'Ex-Out Creativity Handbook',
    tagline: 'Mobile app & design assets for activism.',
  },
  {
    id: 307,
    name: 'Adjustments',
    tagline: 'Essential Figma plugin for simultaneous HSL color adjustment',
  },
  {
    id: 308,
    name: 'DefeatBOCO - Research World',
    tagline: 'An immersive journey into what UX is and why it matters.',
  },
  {
    id: 309,
    name: 'Funder',
    tagline: 'Create your own parody slogans for "world-changing" startups',
  },
  {
    id: 310,
    name: 'Possessions.',
    tagline: 'A zen game with a story told without any dialogue',
  },
  {
    id: 311,
    name: 'StartupThreads Shopify App',
    tagline: 'Easily Sell custom tshirts in your shopify store',
  },
  {
    id: 312,
    name: 'Georgette Packaging',
    tagline: 'Branded packaging accessible to anybody who needs it',
  },
  {
    id: 313,
    name: 'Domain Inferno',
    tagline: 'Browse recently expired, pronounceable domain names',
  },
  {
    id: 314,
    name: 'AIFE.AI',
    tagline: 'Launch a big digital footprint in 60 seconds 👣',
  },
  {
    id: 315,
    name: 'xroom.app',
    tagline: 'Providing secure, simple and encrypted video conferencing',
  },
  {
    id: 316,
    name: 'Custom by Sock Club',
    tagline: 'Quality custom socks for your company',
  },
  {
    id: 317,
    name: 'LonelyPage',
    tagline: 'Create and design your landing, event, business in one page',
  },
  {id: 318, name: '-', tagline: '-'},
  {
    id: 319,
    name: 'Reward Attention',
    tagline: 'Trigger donations on climate or Covid-19 by taking surveys',
  },
  {
    id: 320,
    name: 'Design for Business',
    tagline: 'User-friendly way to generate profits',
  },
  {
    id: 321,
    name: 'Brandpad',
    tagline: 'Host your brand guidelines and assets in the cloud',
  },
  {
    id: 322,
    name: 'Linkcard',
    tagline: 'Create stunning digital business cards',
  },
  {
    id: 323,
    name: 'Reviewerly',
    tagline: 'Boost text, photo, and Instagram reviews with Messenger.',
  },
  {
    id: 324,
    name: 'The Name App',
    tagline: 'Find an available name for your next brilliant idea',
  },
  {id: 325, name: 'Herb & Olive', tagline: 'Elevate your cooking'},
  {
    id: 326,
    name: 'Videobolt 2.0',
    tagline: 'Professional design for your videos, no software required!',
  },
  {
    id: 327,
    name: 'Tenta Browser 2.0',
    tagline: 'Next gen VPN, total browser encryption & decentralized trust',
  },
  {
    id: 328,
    name: 'Obsidian Premium Tees',
    tagline: 'High quality shirts for the daily minimalist.',
  },
  {id: 329, name: 'UpLevo', tagline: 'Design your logo in 2 clicks'},
  {id: 330, name: 'Logophile', tagline: 'Learn new words as you surf the web'},
  {
    id: 331,
    name: 'Mention ✪ Insights Center',
    tagline: 'Measure your brand performance any way you need to 👋',
  },
  {
    id: 332,
    name: 'Personal Print',
    tagline: 'Automated personalized Thank-You notes for Shopify',
  },
  {
    id: 333,
    name: "Un'kuppd Portable Pourover Coffee",
    tagline: 'Single cup, specialty grade coffee you can take anywhere',
  },
  {
    id: 334,
    name: 'Draftss',
    tagline: 'Unlimited graphic design at $259 per month',
  },
  {
    id: 335,
    name: 'Gatekeepr',
    tagline: 'Grow your brand with deep analysis on social media',
  },
  {
    id: 336,
    name: 'AmpAve',
    tagline: 'Collect, curate, and publish authentic customer experiences.',
  },
  {
    id: 337,
    name: 'Mailjoy Letters',
    tagline: 'Send personalized direct mail letter campaigns',
  },
  {
    id: 338,
    name: 'terrible colors',
    tagline: 'Just a collection of dumpster-fire, garbage colors.',
  },
  {
    id: 339,
    name: 'This is Broken',
    tagline: "A tribute to Seth Godin's book recommendations",
  },
  {
    id: 340,
    name: 'Pupprrr',
    tagline: "Don't have a dog? This app let's you play with one!",
  },
  {
    id: 341,
    name: 'News apps by PressPad',
    tagline: 'WordPress to apps. A native news apps platform.',
  },
  {id: 342, name: 'Slidesome', tagline: 'Live slideshow for any occasion'},
  {
    id: 343,
    name: 'Gradient Joy',
    tagline: 'Beautiful gradients as placeholder images just for you',
  },
  {
    id: 344,
    name: 'Joy Milk Tea',
    tagline: 'Tell coffee you need a break. Real milk tea.',
  },
  {
    id: 345,
    name: 'Flat Icon Generator 2.0',
    tagline: 'Offline-ready webapp for creating flat, Android-style icons.',
  },
  {
    id: 346,
    name: 'HostEvent',
    tagline: 'Create an event app in 3 easy steps under 30 minutes',
  },
  {
    id: 347,
    name: 'TAG : Next-Gen Social Network',
    tagline: 'Purpose driven, micro-communities',
  },
  {
    id: 348,
    name: 'LivMo',
    tagline: 'Book from a curated collection of great experiences easily',
  },
  {
    id: 349,
    name: 'Wordoid',
    tagline: 'Most creative way to find a catchy name for your new venture',
  },
  {
    id: 350,
    name: 'Local mail by Mailjoy',
    tagline: 'An easy way to market locally with mail',
  },
  {
    id: 351,
    name: 'Waka Coffee',
    tagline: 'Forget what you know about instant coffee.',
  },
  {
    id: 352,
    name: 'Foo Fighters Sky',
    tagline: 'Explore the sky in your neighborhood with Foo Fighters',
  },
  {
    id: 353,
    name: 'Naming Matters',
    tagline: 'A new, affordable naming startup for startups',
  },
  {
    id: 354,
    name: 'bulk-mail CLI',
    tagline: 'Do hassle-free email marketing with this powerful tool 🔥',
  },
  {
    id: 355,
    name: 'Knowee',
    tagline: 'Digital business cards that are easily shared and searched',
  },
  {
    id: 356,
    name: 'favico.js',
    tagline: "Use badges, images or videos with your website's favicon",
  },
  {
    id: 357,
    name: 'DrawAttention: The Blackboard',
    tagline: 'A blackboard for your laptop lid',
  },
  {
    id: 358,
    name: 'Klasmic',
    tagline: 'Create interactive Facebook live videos in few clicks',
  },
  {
    id: 359,
    name: 'Houndr',
    tagline: 'An everyday support system for life in the city with dogs.',
  },
  {
    id: 360,
    name: 'Galaxia',
    tagline: 'Mini social networks for all your personas ',
  },
  {
    id: 361,
    name: 'Placeit Print',
    tagline: 'Free business card, brochure, posters & packaging mockups',
  },
  {
    id: 362,
    name: 'Logo Design',
    tagline: 'E-book about full creative path to effective branding',
  },
  {
    id: 363,
    name: 'DataSkimmer',
    tagline: "Share files the way you'd want to receive them",
  },
  {
    id: 364,
    name: 'Brand Trust Platform by Conversio',
    tagline: 'Empower your customers to represent your true brand.',
  },
  {
    id: 365,
    name: 'Hipster Business Name',
    tagline: 'Generate a name and logo for your hipster business',
  },
  {
    id: 366,
    name: 'Watermarker Pro',
    tagline: 'Protect your images, promote your brand',
  },
  {
    id: 367,
    name: 'Hook',
    tagline: 'Access documents most relevant to your current task',
  },
  {
    id: 368,
    name: 'Safari Beauty Toolbar',
    tagline: 'Make Safari toolbar more consistent with your brand colors',
  },
  {
    id: 369,
    name: 'elStartup',
    tagline: 'A hand-picked directory of the Best resources for Startups',
  },
  {
    id: 370,
    name: 'Tylio',
    tagline: 'Automatic smart web pages - Better stories for your content.',
  },
  {
    id: 371,
    name: 'Moodie: Change your Mood',
    tagline: 'Track and change your mood throughout the day',
  },
  {
    id: 372,
    name: 'Slogan Generator',
    tagline: 'Get hundreds of slogan ideas for your project or business',
  },
  {id: 373, name: 'LogoHold', tagline: 'Show off your logo design projects'},
  {
    id: 374,
    name: 'raw.',
    tagline: "Natural men's hair products in biodegradable containers",
  },
  {
    id: 375,
    name: 'Deconditioning Stickers',
    tagline: 'Stickers designed to mess with your notification addiction',
  },
  {id: 376, name: 'Posyt', tagline: 'Tinder for ideas'},
  {id: 377, name: 'Zap', tagline: 'We replace the business card'},
  {
    id: 378,
    name: 'Conceptboard',
    tagline: 'Visual collaboration platform for marketing and remote teams',
  },
  {id: 379, name: 'Bittenfruit', tagline: 'Mac sticker store'},
  {id: 380, name: 'Swipe Designs', tagline: 'Auto create social media posts'},
  {
    id: 381,
    name: '43 Layers',
    tagline: 'Teespring for event decorations and gifts',
  },
  {
    id: 382,
    name: 'Instant Domain Search',
    tagline: 'See Domain Name Search Results As You Type',
  },
  {
    id: 383,
    name: 'Tinder for Tinders',
    tagline: 'Swipe through Tinder-for-X ideas',
  },
  {
    id: 384,
    name: 'Sesame Corporate Gifts',
    tagline: 'Unique co-branded gifts for companies',
  },
  {
    id: 385,
    name: 'Packamatic',
    tagline: 'On demand packaging boxes with your logo',
  },
  {
    id: 386,
    name: 'Greetabl for Business',
    tagline: 'Better than a greeting card, more personal than flowers.',
  },
  {
    id: 387,
    name: 'Hipster Logo Generator',
    tagline: "It's Hip, It's Current, It's Stylish, It's Hipster.",
  },
  {
    id: 388,
    name: 'Visura.co',
    tagline: 'Build your website and connect with the media industry.',
  },
  {
    id: 389,
    name: 'Far Fetched Creations',
    tagline: 'One-of-a-kind startup swag',
  },
  {
    id: 390,
    name: 'Made for Motion: Backpack & Packing Kit',
    tagline: 'A simple and functional carrying solution.',
  },
  {id: 391, name: 'Go Jauntly', tagline: 'Discover walks & happiness outdoors'},
  {
    id: 392,
    name: 'Vyrill',
    tagline: "Deep, A.I. 'in-video' analysis & fan video content marketing",
  },
  {
    id: 393,
    name: 'Web Push Notifications',
    tagline: 'Rethink remarketing with relevant product reminders',
  },
  {id: 394, name: 'Lnky', tagline: 'The fastest way to share yourself.'},
  {
    id: 395,
    name: 'OnBrand Grader',
    tagline: 'Free tool to grade your branding in seconds',
  },
  {id: 396, name: 'Hashletes', tagline: 'Digital Tokens for NFL Players'},
  {id: 397, name: 'Brandy', tagline: 'A brand asset manager for your menu bar'},
  {
    id: 398,
    name: 'MOO Letter Press Cards',
    tagline: 'Some lovely looking letterpress business cards',
  },
  {id: 399, name: 'litty', tagline: 'Find lit clubs & bars near you'},
  {
    id: 400,
    name: 'Vyrill VIP',
    tagline: 'Discover and connect with video influencers for your brand',
  },
  {
    id: 401,
    name: 'Base Deploy',
    tagline: 'Build powerful apps faster - without coding',
  },
  {
    id: 402,
    name: 'Underdog.io Workplaces',
    tagline: 'Unsponsored documentary profiles of business and culture',
  },
  {
    id: 403,
    name: 'Floom',
    tagline: "Send stunning flowers from NY's and London's best florists",
  },
  {id: 404, name: 'EmojiCatch', tagline: 'Search 17 emoji domains for free'},
  {
    id: 405,
    name: 'ScrapeLogo',
    tagline: 'Get logos for site/app with this dead-simple HTML API',
  },
  {
    id: 406,
    name: 'Guide to Community Building',
    tagline: 'The Mighty Networks Guide to Building Communities Online',
  },
  {
    id: 407,
    name: 'Digital Profile',
    tagline: 'Matching digital & tech professionals to jobs',
  },
  {
    id: 408,
    name: 'Lanyard Market',
    tagline: 'Design & order promotional items for your company in minutes',
  },
  {
    id: 409,
    name: 'Harmany',
    tagline: 'Find or offer shelter during emergencies and evacuations 🏠🌀🔥',
  },
  {id: 410, name: 'Squarespace Logo', tagline: 'A do-it-yourself logo builder'},
  {id: 411, name: 'Meed Influencers', tagline: 'Build your brand'},
  {
    id: 412,
    name: 'Touristerguide Wand',
    tagline: 'Send WhatsApp messages to anyone without saving their number',
  },
  {
    id: 413,
    name: 'SoProSearch',
    tagline: 'Advanced social media search. Ultimate social selling tool!',
  },
  {id: 414, name: 'Sinup', tagline: 'The digital swear jar app'},
  {
    id: 415,
    name: 'Captain Share',
    tagline: 'Curated directory of sharing economy resources to save money',
  },
  {
    id: 416,
    name: 'LogoGraders',
    tagline: 'Free, human-reviewed logo report cards',
  },
  {id: 417, name: 'Foliodot', tagline: 'Simplest, versatile portfolio website'},
  {id: 418, name: 'Quiddity', tagline: 'Nonfiction made Simple'},
  {id: 419, name: 'Vrumble 2.0', tagline: 'Livestream your Squad and Game!'},
  {id: 420, name: 'Slogan', tagline: 'Generate logos for open-source projects'},
  {
    id: 421,
    name: 'Zoklean',
    tagline: 'Taking the hassle out of finding an awesome cleaning service',
  },
  {
    id: 422,
    name: 'Reddit Comment Embeds',
    tagline: 'Embed Reddit comments on your website ',
  },
  {
    id: 423,
    name: 'Openned By Erin',
    tagline: 'Handwritten direct mail campaigns',
  },
  {id: 424, name: 'Ace Tutor', tagline: 'Achieve Your Potential!'},
  {
    id: 425,
    name: 'Emoji Rags',
    tagline: 'T-shirts and apparel with ultra-hip sayings 💯 💵 💪 🔥',
  },
  {
    id: 426,
    name: 'Alerts by MarketSpace',
    tagline: 'Company monitoring, customized, curated & delivered anywhere',
  },
  {
    id: 427,
    name: 'Like & Subscribe',
    tagline: 'A Podcast about YouTube culture',
  },
  {id: 428, name: 'Pickit', tagline: "The world's simplest DAM system"},
  {id: 429, name: 'Ebroji', tagline: 'The first curated GIF keyboard'},
  {
    id: 430,
    name: 'BrandBucket',
    tagline: 'Largest resource of unique .com domain names.',
  },
  {
    id: 431,
    name: 'Missions Dashboard from EyeEm',
    tagline: 'Source images from 20mm photographers and measure engagement',
  },
  {
    id: 432,
    name: 'Vidooya',
    tagline: 'Turn your blogs into videos with three simple steps',
  },
  {
    id: 433,
    name: 'Lean Branding',
    tagline: 'Build your own dynamic brand that generates conversions',
  },
  {
    id: 434,
    name: 'Name Geniuses',
    tagline: 'A pay-what-you-want crowdsourcing business name service.',
  },
  {id: 435, name: 'Ruutly', tagline: 'Embeddable interactive job ads'},
  {
    id: 436,
    name: 'Instagram Marketing for Beginners',
    tagline: 'How to build a brand',
  },
  {
    id: 437,
    name: 'Aim.io',
    tagline: 'Aim.io: a non-intrusive, most-effective ad network.',
  },
  {
    id: 438,
    name: 'OneHoodie',
    tagline: 'Represent multiple projects and companies',
  },
  {
    id: 439,
    name: 'Fifty Square Feet Productions',
    tagline: 'Production house. We partner brands with great stories. ',
  },
  {id: 440, name: 'ThugStart', tagline: 'If You Begin, You Win.'},
  {
    id: 441,
    name: 'InstantDJ',
    tagline: 'A DJ simulator created from an Instagram Stories hack.',
  },
  {
    id: 442,
    name: 'Brand Identity Breakthrough',
    tagline: "Craft your company's story & make your products irresistible",
  },
  {
    id: 443,
    name: 'Emotional Branding',
    tagline: 'The new paradigm for connecting brands to people',
  },
  {
    id: 444,
    name: 'Chevrolet Co-Driver',
    tagline: 'Get tips for staying on top of your resolutions',
  },
  {
    id: 445,
    name: 'TIC - From Bonobos to the Warby Parker of Furniture',
    tagline: 'A chat with Rob Royer / Founder of Interior Define',
  },
  {
    id: 446,
    name: 'Brand Ballers - Maintain a fresh website so your visitors have a good experience',
    tagline: 'Fresh website creates more referrals',
  },
  {
    id: 447,
    name: "Breaking Down Your Business: School's Out!",
    tagline: "On Matt Miller's ingenious business & summer vacations!",
  },
  {
    id: 448,
    name: 'SMB Trust Rating',
    tagline: 'Net promoter score for some of the biggest businesses',
  },
  {
    id: 449,
    name: 'What Makes A Great Brand & How To Cut Through All The Noise',
    tagline: 'A chat with David Gardner, founder of ColorJar',
  },
  {
    id: 450,
    name: 'BRAND24',
    tagline: 'A powerful, award-winning app for media monitoring 🚀',
  },
  {
    id: 451,
    name: 'Social Media',
    tagline: 'Strategies for mastering your brand',
  },
  {
    id: 452,
    name: 'Learn Educate Discover: Uttam Mukherjee, Brand Manager @P&G',
    tagline: 'What does a Brand Manager in CPG do?',
  },
  {
    id: 453,
    name: 'Ambition Today #14: Adam Besvinick Teaches How To Break Into Startups & Venture Capital',
    tagline: 'The art of hustle and how to break into your dream role',
  },
  {
    id: 454,
    name: 'Ambition Today - 15: How Patrick McGinnis',
    tagline: 'How Patrick coined the term FOMO on the internet!',
  },
  {
    id: 455,
    name: 'Breaking Down Your Business Ep #190 - Kelly Jurecko',
    tagline: 'Top 5 ways to stay the course',
  },
  {
    id: 456,
    name: 'Breaking Down Your Business Ep #172',
    tagline: 'Top 5 ways to get someone’s attention without being a pest',
  },
  {
    id: 457,
    name: 'The Twenty Minute VC: Branko Cerny @ Immediately',
    tagline: 'The rise of bottoms up sales and branding in SaaS',
  },
  {
    id: 458,
    name: 'Digital Good Times - Ep 65 - Kerry Klassic of Intecoo - The Era of Brands & Influencer Marketing',
    tagline: 'The power of brands and influencers',
  },
  {
    id: 459,
    name: 'Seedcamp Podcast: Marketing Guru, Katy Turner',
    tagline: 'Company DNA and creating brands with purpose',
  },
  {
    id: 460,
    name: 'FOMOFanz 006: How I Define Success in a Digital World',
    tagline: 'Why you must define success before thinking about the tech!',
  },
  {
    id: 461,
    name: 'Breaking Down Your Business Ep #189',
    tagline: 'Top 5 signs you need to switch things up w/ Niala Boodhoo',
  },
  {
    id: 462,
    name: 'Breaking Down Your Business Ep #176',
    tagline: '5 Craziest moments in your business owner life',
  },
  {
    id: 463,
    name: 'Breaking Down Your Business Ep #177',
    tagline: 'Top 5 scariest things for your business',
  },
  {
    id: 464,
    name: 'Create If Writing: How to Work with Brands and Tell Your Story in Sponsored Content',
    tagline: 'Food blogger Rachel Matthews shares her best practices',
  },
  {
    id: 465,
    name: 'Breaking Down Your Business - Driving Yourself Crazy?',
    tagline: "Top 5 ways you're driving YOURSELF crazy - And how to stop",
  },
  {
    id: 466,
    name: 'Hack To Start #124: Hailley Griffis, Communications Specialist, Buffer',
    tagline: "Building a brand and what it's like at Buffer",
  },
  {
    id: 467,
    name: "BrandBallers - #40 - Mike's first draft of a video script",
    tagline: 'Behind the scenes of making a promo video',
  },
  {
    id: 468,
    name: 'Learn Educate Discover: How To Build Your Brand Using Quora, Zach Pinnell, Founder @BlogToJob.com',
    tagline: 'Strategically answering questions on Quora to get more views',
  },
  {
    id: 469,
    name: 'Breaking Down Your Business Ep #175',
    tagline: 'Top 5 ways to have more committed and engaged employees',
  },
  {
    id: 470,
    name: 'Breaking Down Your Business - Ryan Dohrn',
    tagline: 'Top 5 ways to tell that the prospect is not that into you',
  },
  {
    id: 471,
    name: 'Brand Boost Podcast - 162: Platforms that Drive Consumer Decisions',
    tagline: 'With Vincenzo Landino & Rob Hix',
  },
  {
    id: 472,
    name: 'Brand Ballers - Marketing: Who to target and how that affects website design',
    tagline: 'Talk about the importance of targeting and the PAS framework',
  },
  {
    id: 473,
    name: 'The Notion Capital - 09: David Shearer, VP Marketing at Elevaate',
    tagline: 'Designing a brand strategy that scales within a startup',
  },
  {
    id: 474,
    name: 'Be The Brand',
    tagline: 'The Ultimate Guide to Building Your Personal Brand',
  },
  {
    id: 475,
    name: 'RGB – #20: RGBA Series 2',
    tagline: 'This week we discuss the redesign of RGBA and the new iPhone',
  },
  {
    id: 476,
    name: 'Brand Ballers - Finding A Blog Process That Speeds Up Workflow',
    tagline: 'Sharing our experiences to find a blog process that works',
  },
  {
    id: 477,
    name: 'Shopify Masters - How a PC Gamer Built a 7-Figure Business That Practically Runs Itself',
    tagline: 'How to turn your passion into a business',
  },
  {
    id: 478,
    name: 'Hello Tech Pros: Lean Startup Process and Talent4Startups.org',
    tagline: 'Rajiv Menon on Entrepreneurship',
  },
  {
    id: 479,
    name: "Boss Girl Creative: Defining Your Niche - Why You Should and/or Shouldn't",
    tagline: 'How important is it to define your niche?',
  },
  {
    id: 480,
    name: 'Breaking Down Your Business - Ep #173',
    tagline: 'Top 5 Reasons Your Labor Costs Are Going UP',
  },
  {
    id: 481,
    name: 'Breaking Down Your Business - Ep #167',
    tagline: 'Top 5 money mistakes small businesses make',
  },
  {
    id: 482,
    name: 'Brand Ballers: What is a website and how it affects your brand',
    tagline: 'Discussing how websites can be used as marketing tools',
  },
  {
    id: 483,
    name: 'BrandBallers Podcast #34 - Recap of our website series',
    tagline: 'Talking about websites helped us improve our websites',
  },
  {
    id: 484,
    name: 'Breaking Down Your Business - Working OUT (Of The Office)',
    tagline: 'Top 5 tools for getting work done ANYWHERE',
  },
  {
    id: 485,
    name: 'BrandBallers Podcast - Episode 38',
    tagline: "Carl's path to 20K Youtube subscribers",
  },
  {
    id: 486,
    name: "Creative Pep Talk - Don't Chase The Glory",
    tagline: "Conversation centered on not chasing ‘design fame'",
  },
  {
    id: 487,
    name: 'Creative South Podcast - Bonus Episode - Hebah',
    tagline: 'How culture and diversity informs design with Hebah',
  },
  {
    id: 488,
    name: 'Breaking Down Your Business Ep #168',
    tagline: 'Top 5 emails you are going to write one million times',
  },
  {
    id: 489,
    name: "Breaking Down Your Business - Lookin' Good",
    tagline: 'Top 5 ways to manage your online reputation!',
  },
  {
    id: 490,
    name: 'Creative South Podcast - Episode 10 - Eric Friedensohn',
    tagline: 'Eric Friedensohn joins us for the Creative South Podcast',
  },
  {
    id: 491,
    name: 'BrandBallers - How User Experience Affects Branding And What People Think About You',
    tagline: 'Talking about user experience for small business websites',
  },
  {
    id: 492,
    name: 'Breaking Down Your Business Podcast Ep #170',
    tagline: 'The Top 5 Wardrobe Mistakes Small Business People Make',
  },
  {
    id: 493,
    name: 'Brand Ballers: Setting Up Your Website Like A Restaurant',
    tagline: 'Discussing 2 ways to build up a website',
  },
  {
    id: 494,
    name: 'TGIM - How SoulCycle’s Founders Built a Nationwide Movement Around Their Brand',
    tagline: '"Don\'t create users, you want to create evangelists."',
  },
  {
    id: 495,
    name: 'Breaking Down Your Business - Get In The Zone',
    tagline: '5 spiritual practices you need to survive self-employment',
  },
  {
    id: 496,
    name: "Breaking Down Your Business - It's Opposite Day! (No it's not)",
    tagline: 'Top 5 things biz owners say that actually mean the opposite',
  },
  {
    id: 497,
    name: 'BrandBallers Podcast - #36',
    tagline: 'Getting started making video with your phone',
  },
  {
    id: 498,
    name: 'Breaking Down Your Business Ep #171: Andrew Schulman',
    tagline: 'The top 5 things to do when you have free time',
  },
  {
    id: 499,
    name: 'BizDevShots Podcast - Turn the Ship Around – Go From a Leaky Deathtrap to a Luxury Yacht',
    tagline: 'We cover a quick hack that will increase your revenue fast',
  },
  {
    id: 500,
    name: 'BrandBallers Podcast - BB#39',
    tagline: 'Video as a sales tool (The tipping point)',
  },
  {
    id: 501,
    name: 'BrandBallers #37 - How to structure videos',
    tagline: '3 action steps to structuring a promo video',
  },
  {
    id: 502,
    name: 'Process - Episode 1 - Divvy Bike Share Chicago',
    tagline: 'A podcast about design, by designers.',
  },
  {
    id: 503,
    name: 'Breaking Down Your Business - Talk To Me',
    tagline: 'Top 5 ways to have better business conversations',
  },
  {
    id: 504,
    name: 'Breaking Down Your Business - Group Hug',
    tagline: 'Top 5 Ways To Get Value Out Of An Online Community',
  },
  {
    id: 505,
    name: 'BrandBallers Podcast - 24: Content Form',
    tagline: 'Choosing form makes you more effective and enjoyable',
  },
  {
    id: 506,
    name: 'Breaking Down Your Business - Get Out The Door (More)',
    tagline: 'Top 5 ways to get out more',
  },
  {
    id: 507,
    name: 'Breaking Down Your Business Podcast - Ep 166',
    tagline: 'Top 5 ways to say "Thank You" to your team',
  },
  {
    id: 508,
    name: 'Dreamit Podcast - Startup Brand Building with Robin Albin & Brielle Pettinelli',
    tagline: 'Tips to create a brand strategy & tell a story effectively',
  },
  {
    id: 509,
    name: 'Objection Co',
    tagline: 'Free review removal chatbot for businesses',
  },
];


